import { expect } from '@esm-bundle/chai';
import { SERVER_HTML } from './fixtures/hello-ssr.html.js';
import { setRenderer } from '../../packages/core/dist/development/vera.js';
import { render as hydratingRender } from '../../packages/renderer/dist/development/vera-renderer-hydrate.js';

/**
 * The SSR → hydration handoff, end to end, for the first time.
 *
 * This could not be tested under jsdom at all: jsdom does not parse
 * `<template shadowrootmode="open">` into a shadow root, so the browser half of the handoff — the
 * half that decides whether adoption works — never happened. `hydrate` sat at 68% lines for that
 * reason.
 *
 * `SERVER_HTML` is real output from `@verajs/ssr`, generated by
 * `scripts/build-hydration-fixture.mjs`, not markup written to match.
 */

setRenderer(hydratingRender);

const frame = () => new Promise((r) => requestAnimationFrame(() => setTimeout(r, 0)));

const parseServerHtml = () => {
  const host = document.createElement('div');
  document.body.appendChild(host);
  /** `setHTMLUnsafe` is what turns declarative shadow DOM into real shadow roots. */
  host.setHTMLUnsafe(SERVER_HTML);
  return host;
};

it('the browser parses declarative shadow DOM into a real shadow root', () => {
  const host = parseServerHtml();
  const el = host.querySelector('hello-ssr');
  expect(el, 'the server element is present').to.not.equal(null);
  expect(el.shadowRoot, 'DSD became a real shadow root — jsdom leaves a <template> here').to.not.equal(null);
  expect(el.shadowRoot.querySelector('h1').textContent).to.contain('hello from the server');
  host.remove();
});

it('hydration adopts the server nodes instead of replacing them', async () => {
  const host = parseServerHtml();
  const el = host.querySelector('hello-ssr');
  const root = el.shadowRoot;

  const serverH1 = root.querySelector('h1');
  const serverInput = root.querySelector('input');
  expect(serverH1, 'server rendered an h1').to.not.equal(null);

  /** Mark the nodes so identity cannot be faked by an equal-looking replacement. */
  serverH1.dataset.serverNode = 'yes';
  if (serverInput) serverInput.dataset.serverNode = 'yes';

  /** Upgrading the element runs connectedCallback -> init -> render, which hydrates. */
  const { default: HelloSsr } = await import('../../tests/fixtures/ssr/hello-ssr.js');
  if (!customElements.get('hello-ssr')) customElements.define('hello-ssr', HelloSsr);
  customElements.upgrade(el);
  await frame();

  const afterH1 = root.querySelector('h1');
  expect(afterH1.dataset.serverNode, 'the SAME h1 node survived — adopted, not rebuilt').to.equal('yes');
  expect(afterH1, 'literally the same object').to.equal(serverH1);

  if (serverInput) {
    const afterInput = root.querySelector('input');
    expect(afterInput.dataset.serverNode, 'the input node was adopted too').to.equal('yes');
    /**
     * Its `.value` IS re-applied, and should be: the template binds `.value=${state.greeting}`, so
     * hydration writing it is the binding doing its job. Adoption preserves node *identity* — it
     * does not mean bound properties go untouched. Anything the component does not bind survives
     * untouched, which is what makes focus and scroll position hold.
     */
    expect(afterInput.value).to.equal('hello from the server');
  }
  host.remove();
});

it('a mismatch falls back to a clean render rather than corrupting the DOM', async () => {
  const host = document.createElement('div');
  document.body.appendChild(host);
  /** Server markup that does NOT match what the component renders. */
  host.setHTMLUnsafe(
    '<hello-ssr><template shadowrootmode="open"><div>totally different</div></template></hello-ssr>'
  );
  const el = host.querySelector('hello-ssr');
  customElements.upgrade(el);
  await frame();

  const root = el.shadowRoot;
  expect(root.querySelector('div'), 'the mismatched markup was cleared').to.equal(null);
  expect(root.querySelector('h1'), 'and the component rendered fresh').to.not.equal(null);
  host.remove();
});
