/**
 * **Light-DOM slots hydrated in a REAL browser, from markup a real server produced.**
 *
 * The jsdom suites cover the mechanics, but three of the things that decide this path are the
 * engine's: how a real parser builds the server's markup, when a custom element upgrades relative
 * to its children, and whether the adopted nodes keep the state only a real browser has (focus, a
 * typed value). `CLAUDE.md` puts it plainly — the jsdom suites are the regression net, browser
 * suites are the release gate — and this path had only ever met the net.
 *
 * The markup is GENERATED by `scripts/build-hydration-fixture.mjs` through the actual server
 * pipeline and `--check`ed in the gate, so this cannot drift into adopting markup no server emits.
 */
import { expect } from '@esm-bundle/chai';
import { SLOTS_HTML } from './fixtures/hello-ssr.html.js';
import { renderInto, renderer } from '../../packages/renderer/dist/development/vera-renderer-hydrate.js';
import { slots, slotted } from '../../packages/renderer/dist/development/vera-renderer-slots.js';
import { html, wire } from '../../packages/core/dist/development/vera.js';

wire([renderer, slots]);
const settle = () => new Promise((resolve) => setTimeout(resolve, 0));
/** The SAME template the fixture's component renders. */
const card = () => html`<article><header><slot name="header"><em>fallback header</em></slot></header><main><slot>default fallback</slot></main></article>`;

const mount = () => {
  const holder = document.createElement('div');
  holder.innerHTML = SLOTS_HTML;
  document.body.appendChild(holder);
  return holder.firstElementChild;
};

it('adopts the server\'s distributed markup in place, keeping every node', async () => {
  const host = mount();
  expect(host.getAttribute('data-vera-slotted') ?? host.querySelector('[data-vera-slotted]')).to.not.equal(
    null,
    'CONTROL: the fixture really carries the server marker'
  );
  const header = host.querySelector('h2');
  const bold = host.querySelector('b');

  renderInto(card(), host);
  await settle();

  expect(host.querySelector('h2')).to.equal(header, 'the server node itself, not a copy');
  expect(host.querySelector('b')).to.equal(bold);
  expect(host.querySelector('header').textContent).to.equal('Hydrated header');
  expect(host.querySelector('main').textContent).to.equal('plain bodybold');
  expect(host.querySelector('slot')).to.equal(null, 'no <slot> survives into the light DOM');
  expect(host.querySelector('[data-vera-slotted]')).to.equal(null, 'and the marker is stripped');
  host.remove();
});

it('comes alive after adoption: fallback returns, and re-slotting redistributes', async () => {
  const host = mount();
  renderInto(card(), host);
  await settle();

  host.querySelector('h2').remove();
  await settle();
  expect(host.querySelector('header').textContent).to.equal('fallback header', 'fallback returned');

  const added = document.createElement('h2');
  added.setAttribute('slot', 'header');
  added.textContent = 'Later';
  host.appendChild(added);
  await settle();
  expect(host.querySelector('header').textContent).to.equal('Later', 'and a live addition lands');
  expect(slotted(host, 'header').map((n) => n.textContent)).to.deep.equal(['Later']);
  host.remove();
});

it('recovers the content the server parked for a slot this template does not have', async () => {
  const host = mount();
  renderInto(card(), host);
  await settle();

  expect(host.textContent).to.not.contain('parked', 'unassigned content is held, not rendered');
  expect(host.querySelector('template[data-vera-unassigned]')).to.equal(null, 'the carrier is consumed');
  expect(slotted(host, 'nowhere').map((n) => n.textContent)).to.deep.equal(['parked'],
    'and it is captured, ready for a state that has that slot');

  /** A later state that DOES have the slot must show it. */
  renderInto(html`<article><aside><slot name="nowhere">none</slot></aside></article>`, host);
  await settle();
  expect(host.querySelector('aside').textContent).to.equal('parked',
    'the round trip completes: server-parked content survives into a later render');
  host.remove();
});
