/**
 * **The three-way comparison.** One application, rendered three ways, compared as DOM.
 *
 *   server   `@verajs/ssr` markup, parsed by the browser, no script — what a reader without
 *            JavaScript sees and what a crawler indexes
 *   client   the same components rendered from scratch by `@verajs/renderer`
 *   hydrate  the server's markup adopted in place by `@verajs/renderer/hydrate`
 *
 * All three must be identical. A hydration mismatch is **silent by design** — the container is
 * cleared and re-rendered, so the page looks perfect and the server work is thrown away — so
 * comparing rendered output alone cannot see it. This suite therefore checks identity as well:
 * nodes the server built must still be the nodes on the page after hydration.
 *
 * Run in iframes rather than three test files because `setRenderer` is page-global: one page can
 * hold one renderer. Three documents in one test is the only way to diff them against each other
 * rather than each against a committed string that could drift with them.
 *
 * The fixtures are generated by `scripts/build-kitchen-fixture.mjs`, which CI re-checks, so the
 * markup here is always what the current serializer emits.
 */
import { expect } from '@esm-bundle/chai';
import { canonical } from '../canonical.mjs';

/** Everything the shell renders, so a gap in one mode is a diff rather than a silent absence. */
const COMPONENTS = [
  'sink-bindings',
  'sink-list',
  'sink-collections',
  'sink-effects',
  'sink-styled',
  'sink-scoped',
  'sink-form',
  'sink-slots',
];

const load = (path) =>
  new Promise((resolve, reject) => {
    const frame = document.createElement('iframe');
    frame.style.cssText = 'position:absolute;width:800px;height:600px;left:-9999px';
    frame.src = path;
    frame.addEventListener('error', reject);
    document.body.appendChild(frame);
    frame.addEventListener('load', () => resolve(frame));
  });

/** Polls rather than sleeps: a fixed wait is the flakiest thing a browser test can do. */
const until = async (predicate, what, timeout = 8000) => {
  const started = performance.now();
  for (;;) {
    let value;
    try {
      value = predicate();
    } catch {
      value = false;
    }
    if (value) return value;
    if (performance.now() - started > timeout) throw new Error(`timed out waiting for ${what}`);
    await new Promise((r) => requestAnimationFrame(() => setTimeout(r, 10)));
  }
};

const shellOf = (frame) => frame.contentDocument.querySelector('sink-shell');

/** A mode is ready when its shell has a shadow root and every component in it has one too. */
const ready = async (frame, label) => {
  await until(() => shellOf(frame)?.shadowRoot?.querySelector('#shell'), `${label}: the shell to render`);
  const root = shellOf(frame).shadowRoot;
  for (const tag of COMPONENTS)
    await until(() => root.querySelector(tag)?.shadowRoot ?? root.querySelector(tag)?.firstElementChild, `${label}: <${tag}>`);
  return shellOf(frame);
};

let ssr;
let csr;
let hydrated;

before(async () => {
  const [a, b, c] = await Promise.all([
    load('/tests/browser/fixtures/kitchen-ssr.html'),
    load('/tests/browser/fixtures/kitchen-csr.html'),
    load('/tests/browser/fixtures/kitchen-hydrate.html'),
  ]);
  /** The server page has no script, so it is ready as soon as the parser has finished with it. */
  ssr = shellOf(a);
  csr = await ready(b, 'client');
  hydrated = await ready(c, 'hydrate');
});

describe('the same application, rendered three ways', () => {
  it('the server page parses into the components it describes', () => {
    expect(ssr, 'no <sink-shell> in the server markup').to.exist;
    expect(ssr.shadowRoot, 'declarative shadow DOM did not become a shadow root').to.exist;
  });

  for (const tag of COMPONENTS) {
    it(`<${tag}> is identical in all three`, () => {
      const of = (shell) => {
        const element = shell.shadowRoot.querySelector(tag);
        expect(element, `<${tag}> missing`).to.exist;
        return canonical(element.shadowRoot ?? element);
      };
      const fromServer = of(ssr);
      const fromClient = of(csr);
      const fromHydrate = of(hydrated);
      expect(fromHydrate, `hydrated differs from the server markup it adopted`).to.equal(fromServer);
      expect(fromClient, `a fresh client render differs from the server`).to.equal(fromServer);
    });
  }

  /**
   * The one place the three modes are *meant* to differ, asserted rather than skipped.
   *
   * A constructed stylesheet cannot be written into markup, so the server emits a `<style>` element
   * — which is what styles the page for a reader with no JavaScript. Once a client adopts the sheet
   * that element is a second copy of the same rules, so `@verajs/styles` removes it. Each mode must
   * end up with exactly one.
   */
  it('each mode applies a component styles exactly once, by one mechanism', () => {
    const count = (shell) => {
      const root = shell.shadowRoot.querySelector('sink-styled').shadowRoot;
      return {
        tags: root.querySelectorAll('style[vera-styles]').length,
        sheets: root.adoptedStyleSheets.length,
      };
    };
    expect(count(ssr), 'the no-JavaScript page must carry its CSS as markup').to.deep.equal({ tags: 1, sheets: 0 });
    expect(count(csr), 'a client render should adopt a constructed sheet').to.deep.equal({ tags: 0, sheets: 1 });
    expect(count(hydrated), 'hydration left the server element behind as well as the sheet').to.deep.equal({
      tags: 0,
      sheets: 1,
    });
  });

  it('the shell itself is identical in all three', () => {
    /** The nav, the outlet and the host attributes — everything outside a child component. */
    const of = (shell) => canonical(shell.shadowRoot).replace(/<sink-[a-z]+ [^>]*>[\s\S]*?<\/sink-[a-z]+>/g, '<component/>');
    expect(canonical(hydrated.shadowRoot)).to.equal(canonical(ssr.shadowRoot));
    expect(of(csr)).to.equal(of(ssr));
  });
});
