/**
 * **The three-way comparison.** One application, rendered three ways, compared as DOM.
 *
 *   server   `@verajs/ssr` markup, parsed by the browser, no script — what a reader without
 *            JavaScript sees and what a crawler indexes
 *   client   the same components rendered from scratch by `@verajs/renderer`
 *   hydrate  the server's markup adopted in place by `@verajs/renderer/hydrate`
 *
 * All three must be identical. A hydration mismatch is **silent by design** — the DOM is repaired
 * in place until it matches the template, so the page looks perfect and the server's work is quietly
 * redone — so comparing rendered output alone cannot see it. This suite therefore checks identity as well:
 * nodes the server built must still be the nodes on the page after hydration.
 *
 * Run in iframes rather than three test files because `setRenderer` is page-global: one page can
 * hold one renderer. Three documents in one test is the only way to diff them against each other
 * rather than each against a committed string that could drift with them.
 *
 * The fixtures are generated by `scripts/build-kitchen-fixture.mjs`, which CI re-checks, so the
 * markup here is always what the current serializer emits.
 */
import { expect } from '@esm-bundle/chai';
import { canonical } from '../canonical.mjs';

/** Everything the shell renders, so a gap in one mode is a diff rather than a silent absence. */
const COMPONENTS = [
  'sink-bindings',
  'sink-list',
  'sink-collections',
  'sink-effects',
  'sink-styled',
  'sink-scoped',
  'sink-form',
  'sink-slots',
];

const load = (path) =>
  new Promise((resolve, reject) => {
    const frame = document.createElement('iframe');
    /**
     * On-screen, deliberately. Firefox and WebKit throttle `requestAnimationFrame` in an iframe
     * that is not being displayed — and the render scheduler *is* `requestAnimationFrame`, so an
     * offscreen frame simply stops updating and every assertion after the first times out. Small
     * and behind the page rather than hidden: `display:none` and `visibility:hidden` throttle too.
     */
    frame.style.cssText =
      'position:fixed;top:0;left:0;width:320px;height:240px;opacity:0.02;border:0;pointer-events:none;z-index:-1';
    frame.src = path;
    frame.addEventListener('error', reject);
    document.body.appendChild(frame);
    frame.addEventListener('load', () => resolve(frame));
  });

/** Polls rather than sleeps: a fixed wait is the flakiest thing a browser test can do. */
const until = async (predicate, what, timeout = 20000) => {
  const started = performance.now();
  for (;;) {
    let value;
    try {
      value = predicate();
    } catch {
      value = false;
    }
    if (value) return value;
    if (performance.now() - started > timeout) throw new Error(`timed out waiting for ${what}`);
    await new Promise((r) => requestAnimationFrame(() => setTimeout(r, 10)));
  }
};

const shellOf = (frame) => frame.contentDocument.querySelector('sink-shell');

/**
 * A live mode is ready when **its own script has run**, not merely when a shadow root exists.
 *
 * The hydrate page is parsed from server markup, so every declarative shadow root is there before
 * a single line of client code executes — waiting on one would measure the server's page and call
 * it the client's. The entry sets `data-sink-mode` as its last act, which is the only signal that
 * the handoff has actually happened.
 */
const ready = async (frame, label) => {
  await until(() => frame.contentDocument.documentElement.dataset.sinkMode === label, `${label}: its entry to run`);
  await until(() => shellOf(frame)?.shadowRoot?.querySelector('#shell'), `${label}: the shell to render`);
  const root = shellOf(frame).shadowRoot;
  for (const tag of COMPONENTS)
    await until(() => root.querySelector(tag)?.shadowRoot ?? root.querySelector(tag)?.firstElementChild, `${label}: <${tag}>`);
  return shellOf(frame);
};

let ssr;
let csr;
let hydrated;

/**
 * Loading three documents takes longer than mocha's 5 s default on Firefox and WebKit, which
 * failed the whole file rather than any assertion in it. A regular function, because `this` is the
 * mocha context.
 */
before(async function loadEveryMode() {
  this.timeout(30000);
  const [a, b, c] = await Promise.all([
    load('/tests/browser/fixtures/kitchen-ssr.html'),
    load('/tests/browser/fixtures/kitchen-csr.html'),
    load('/tests/browser/fixtures/kitchen-hydrate.html'),
  ]);
  /** The server page has no script, so it is ready as soon as the parser has finished with it. */
  ssr = shellOf(a);
  csr = await ready(b, 'csr');
  hydrated = await ready(c, 'hydrate');
});

describe('the same application, rendered three ways', () => {
  /** Three applications in three documents; mocha's 5 s default is for unit tests. */
  beforeEach(function raiseTheTimeout() {
    this.timeout(30000);
  });

  it('the server page parses into the components it describes', () => {
    expect(ssr, 'no <sink-shell> in the server markup').to.exist;
    expect(ssr.shadowRoot, 'declarative shadow DOM did not become a shadow root').to.exist;
  });

  for (const tag of COMPONENTS) {
    it(`<${tag}> is identical in all three`, () => {
      const of = (shell) => {
        const element = shell.shadowRoot.querySelector(tag);
        expect(element, `<${tag}> missing`).to.exist;
        return canonical(element.shadowRoot ?? element);
      };
      const fromServer = of(ssr);
      const fromClient = of(csr);
      const fromHydrate = of(hydrated);
      expect(fromHydrate, `hydrated differs from the server markup it adopted`).to.equal(fromServer);
      expect(fromClient, `a fresh client render differs from the server`).to.equal(fromServer);
    });
  }

  /**
   * The one place the three modes are *meant* to differ, asserted rather than skipped.
   *
   * A constructed stylesheet cannot be written into markup, so the server emits a `<style>` element
   * — which is what styles the page for a reader with no JavaScript. Once a client adopts the sheet
   * that element is a second copy of the same rules, so `@verajs/styles` removes it. Each mode must
   * end up with exactly one.
   */
  it('each mode applies a component styles exactly once, by one mechanism', () => {
    const count = (shell) => {
      const root = shell.shadowRoot.querySelector('sink-styled').shadowRoot;
      return {
        tags: root.querySelectorAll('style[vera-styles]').length,
        sheets: root.adoptedStyleSheets.length,
      };
    };
    expect(count(ssr), 'the no-JavaScript page must carry its CSS as markup').to.deep.equal({ tags: 1, sheets: 0 });
    expect(count(csr), 'a client render should adopt a constructed sheet').to.deep.equal({ tags: 0, sheets: 1 });
    expect(count(hydrated), 'hydration left the server element behind as well as the sheet').to.deep.equal({
      tags: 0,
      sheets: 1,
    });
  });

  /**
   * The other intended divergence: a **lazily loaded** component cannot exist server-side.
   *
   * Fetching `<sink-lazy>` is what the autoloader does when the element enters a live DOM, and a
   * server has neither. The markup therefore carries the empty custom element — which is correct,
   * and is what lets the client fill it — so the comparison below excludes it and this asserts it.
   */
  it('a lazily loaded component is empty on the server and present in both live modes', async () => {
    expect(ssr.shadowRoot.querySelector('sink-lazy').shadowRoot, 'the server cannot autoload').to.equal(null);
    for (const [label, shell] of [['client', csr], ['hydrate', hydrated]]) {
      const lazy = await until(
        () => shell.shadowRoot.querySelector('sink-lazy')?.shadowRoot?.querySelector('#lazy'),
        `${label}: <sink-lazy> to autoload`
      );
      expect(lazy.textContent).to.equal('loaded on demand');
    }
  });

  it('the shell itself is identical in all three', () => {
    /** Everything the shell renders, with the one thing a server cannot produce left out. */
    const of = (shell) =>
      canonical(shell.shadowRoot).replace(/<sink-lazy [^>]*>[\s\S]*?<\/sink-lazy>/, '<sink-lazy/>');
    expect(of(hydrated)).to.equal(of(ssr));
    expect(of(csr)).to.equal(of(ssr));
  });
});
