/**
 * The server→client handoff for motion — stage 7's browser truth.
 *
 * `MOTION_CSS`/`MOTION_BODY` are real `renderMotion` output, generated by
 * `scripts/build-motion-fixture.mjs` (whose `--check` is in the gate). Two claims only a real
 * engine can make:
 *
 * 1. **Frame 0 paints from the emitted CSS with no vera JavaScript at all** — the first-frame
 *    defect this stage exists to close. Before it, a fade-up arrived visible, snapped hidden at
 *    activation, then animated; here the computed opacity is 0 before any wiring happens.
 * 2. **The client re-derives the same identities and takes over the same elements** — the
 *    determinism half: markers unchanged after wiring (FNV-1a over the same generated text), and
 *    the driven variable appears, meaning the server-marked element is now the client's.
 */
import { expect } from '@esm-bundle/chai';
import { MOTION_CSS, MOTION_BODY, MOTION_MARKERS, MOTION_REPORT } from './fixtures/motion-ssr.html.js';

const frame = () => new Promise((r) => requestAnimationFrame(r));

it('frame 0 paints from server CSS alone, and the client takes over the same identities', async () => {
  /** The server's page, verbatim — style first, exactly as <head> precedes <body>. */
  const style = document.createElement('style');
  style.textContent = MOTION_CSS;
  document.head.appendChild(style);
  const host = document.createElement('div');
  host.innerHTML = MOTION_BODY;
  document.body.appendChild(host);
  await frame();

  /** CLAIM 1 — no vera JavaScript has loaded, and the animation IS the initial frame. */
  const fade = host.querySelector('#fade');
  expect(getComputedStyle(fade).filter, 'the fade arrives hidden, not visible-then-snapping')
    .to.match(/opacity\(0\)/);
  expect(getComputedStyle(fade).transform, 'and displaced to its start').to.not.equal('none');
  const grouped = host.querySelector('#grouped');
  expect(getComputedStyle(grouped).filter, 'an easing-group split paints frame 0 too')
    .to.match(/opacity\(0\)/);
  expect(fade.getAttribute('data-vd-a'), 'marked by the server')
    .to.equal(MOTION_MARKERS.fade);
  /** Since 8a the stagger member paints frame 0 TOO — marked, its offset inline from the
   *  server, sharing rules with any twin (the offset is a var, not a rule fork). */
  expect(host.querySelector('#member').getAttribute('data-vd-a'),
    'the stagger member paints server-side since 8a').to.equal(MOTION_MARKERS.member);
  expect(MOTION_REPORT.rendered, 'the fixture really covered the page').to.equal(6);

  /** Transition-mode play arrives PRE-ARMED: base paints with the longhands already legal
   *  (first paint IS base, so nothing fires), and no seek variable exists for it. */
  const tplay = host.querySelector('#tplay');
  expect(tplay.getAttribute('data-vd-a'), 'marked').to.equal(MOTION_MARKERS.tplay);
  expect(tplay.hasAttribute('data-vera-t'), 'pre-armed in markup').to.equal(true);
  expect(getComputedStyle(tplay).filter, 'base paints — a play element arrives at its start')
    .to.match(/opacity\(0\.15/);

  /** CLAIM 2 — wire the client on top of the server's page. */
  const { wireDirectives, motion, presets } = await import(
    '../../packages/directives/dist/development/vera-directives.js');
  wireDirectives([motion({ inertia: 0 }), presets]);
  await frame();
  await new Promise((r) => setTimeout(r, 60));
  await frame();

  for (const [id, marker] of Object.entries(MOTION_MARKERS)) {
    expect(host.querySelector(`#${id}`).getAttribute('data-vd-a'),
      `${id}: the client re-derived the server's identity byte for byte`).to.equal(marker);
  }
  expect(fade.style.getPropertyValue('--vd-p'), 'and the client is driving the seek now')
    .to.not.equal('');
  /** The stagger member activates client-side as ever — the skipped shape still works. */
  expect(getComputedStyle(host.querySelector('#member')).filter).to.match(/opacity\(/);

  /** No duplicate-registration fallout: the server's @property plus the client's
   *  CSS.registerProperty must coexist silently. */
  const { rejections } = await import(
    '../../packages/directives/dist/development/vera-directives.js');
  expect(rejections().some((r) => r.code === 'motion-progress-property-taken'),
    'declarative @property and API registration coexist').to.equal(false);
});
