import vera from '@verajs/eslint-config';
import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * Scope first. Without `ignores`, this linted `dist/` (generated bundles, mangled and minified)
 * and `internal/` (a separate private repository cloned into this tree and gitignored here) —
 * together ~2 200 of ~2 230 reported problems, which made the real ones unfindable.
 *
 * Globals are per area rather than global-browser-everywhere: the build scripts, benchmarks, tests
 * and `@verajs/ssr` are Node, and telling eslint that `process` is a browser global is how
 * `defaultRollupConfig.js` ended up carrying an eslint-disable comment for a legitimate use.
 */
export default [
  {
    ignores: [
      '**/dist/**',
      // Generated from @verajs/ssr's JSDoc at build time — output, like dist, not source.
      'packages/ssr/types/**',
      // wireit's build cache holds copies of every output; `**/dist/**` never covered them.
      '**/.wireit/**',
      // A separate repo (vera-js/internal), gitignored here. Not ours to lint.
      'internal/**',
      // Same arrangement: vera-js/vera-studio, cloned into this tree and gitignored here.
      'vera-studio/**',
      '**/*.min.js',
      'bench/.size-*/**',
      /**
       * Ad-hoc audit probes. `.gitignore` has carried `.probe/` since the day a probe was swept into
       * a commit, but eslint has its own ignore list and did not — so a probe left in the tree fails
       * the gate on `no-unused-vars` in code nobody wrote by hand. It cost two gate runs in one
       * afternoon, once at the root and once under `bench/`.
       */
      '**/.probe/**',
      /** Generated by `node bench/dom/build.mjs` — a bundle, and this repo never lints or commits one. */
      'bench/dom/bundle.js',
      /** A gitignored symlink into the private portal (the motion measurement harnesses). */
      'packages/motion/spikes/**',
    ],
  },
  { files: ['**/*.{js,mjs,cjs,ts}'] },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      /** `_`-prefixed means deliberately unused here, matching the `_internal` mangling convention. */
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      /**
       * `packages/jsx/src/parser.js` carries a zero-width space inside `*\u200b/` so a doc comment
       * can show `{/* … *\u200b/}` without terminating itself. It is load-bearing — do not "tidy"
       * it away.
       */
      'no-irregular-whitespace': ['error', { skipComments: true }],
      /** `try { unlink(tmp) } catch {}` in test teardown is the intent, not an oversight. */
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },

  /** Library and example sources run in a browser. */
  {
    files: ['packages/*/src/**/*.{js,ts}', 'examples/**/*.{js,ts}'],
    languageOptions: { globals: { ...globals.browser, __DEV__: 'readonly' } },
    /**
     * The VeraJS rules come from our own published config, so the package is exercised by every
     * `npx eslint .` here rather than only by its own tests. It carries the reasoning for both
     * rules; in short, they cover the two mistakes that produce no error at all — a class field on
     * a custom element, and taking `insert` from `@verajs/inserts` instead of the owning package.
     *
     * Only `.rules` is taken, not the config object: spreading that would replace the `files` scope
     * above with the package's own repo-wide glob, widening the browser globals to everything and
     * failing the suites that violate both rules deliberately in order to test them.
     */
    rules: { ...vera[0].rules },
  },

  /**
   * The two packages that own the insert surface re-export it on purpose.
   *
   * `export * from '@verajs/inserts'` is what makes `insert` available *from core* and *from
   * router* — each bundle re-exporting its own inlined copy is precisely the thing the rule exists
   * to steer consumers toward. ESLint counts a star re-export as importing every restricted name,
   * which is right for consumer code and wrong for the two modules defining the API.
   */
  {
    files: ['packages/core/src/index.ts', 'packages/router/src/index.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  /**
   * The test harnesses are deliberately dependency-free and every one of them counts results with
   * `cond ? pass++ : (fail++, console.log('FAIL:', name))`. Both halves do work, so the rule is
   * simply wrong here — and `allowTernary` does not cover it, because what it objects to is the
   * comma operator in the else branch, not the ternary. Off for tests rather than rewriting
   * thirteen working harnesses to satisfy it.
   */
  {
    files: ['tests/**/*.mjs'],
    rules: { '@typescript-eslint/no-unused-expressions': 'off' },
  },

  /**
   * Browser suites. `it`/`describe` come from the test runner's framework, the code runs in a real
   * browser, and chai's `expect(x).to.be.true` is an expression statement by design — the rule
   * cannot tell it from a mistake.
   */
  {
    files: ['tests/browser/**/*.js'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.mocha },
    },
    rules: { '@typescript-eslint/no-unused-expressions': 'off' },
  },

  /**
   * Svelte rune modules. `$state` and friends are compiler intrinsics, not imports — they exist
   * only until `svelte/compiler` rewrites them, so eslint has no way to know they are legitimate.
   */
  {
    files: ['**/*.svelte.js'],
    languageOptions: {
      globals: { $state: 'readonly', $derived: 'readonly', $effect: 'readonly', $props: 'readonly' },
    },
  },

  /**
   * `@verajs/motion` came in with its own gate (2026-09-01 migration). Its tests run under
   * `node --test` with happy-dom registered on globalThis, and its scripts are Node programs
   * that drive a browser DOM — so both worlds' globals are real in both.
   */
  {
    files: ['packages/motion/{test,scripts}/**/*.{js,mjs}'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },

  /** Build tooling, benchmarks, tests and the example servers run in Node. */
  {
    files: [
      '*.js',
      '*.mjs',
      'scripts/**/*.{js,mjs}',
      'bench/**/*.{js,mjs}',
      'tests/**/*.{js,mjs}',
      'packages/*/rollup.config.js',
      'packages/ssr/**/*.{js,mjs}',
      'examples/**/serve.js',
      'examples/**/server*.{js,mjs}',
    ],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
];
