/**
 * The surface a real element, shadow root, document and stylesheet expose, taken from Chromium, Firefox and WebKit.
 *
 * `@verajs/ssr`'s server DOM was extended reactively for its whole life: every missing member was
 * found by someone tripping over it, one at a time. This is the list it is held to, so a gap fails a
 * test instead of a render. It is data, not code — no dependency parses or derives it.
 *
 * **Regenerating:** `tests/browser/dom-surface.test.js` fails when an engine exposes something not
 * listed here, and prints the names. Add each one either to the shim or to `OUT_OF_SCOPE` with the
 * reason it cannot work on a server.
 *
 * `on*` event handlers are excluded — there are hundreds, and none of them reach markup.
 */
export const SURFACES = {
  "element": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "accessKey",
    "accessKeyLabel",
    "activeViewTransition",
    "addEventListener",
    "after",
    "animate",
    "append",
    "appendChild",
    "ariaActionsElements",
    "ariaActiveDescendantElement",
    "ariaAtomic",
    "ariaAutoComplete",
    "ariaBrailleLabel",
    "ariaBrailleRoleDescription",
    "ariaBusy",
    "ariaChecked",
    "ariaColCount",
    "ariaColIndex",
    "ariaColIndexText",
    "ariaColSpan",
    "ariaControlsElements",
    "ariaCurrent",
    "ariaDescribedByElements",
    "ariaDescription",
    "ariaDetailsElements",
    "ariaDisabled",
    "ariaErrorMessageElements",
    "ariaExpanded",
    "ariaFlowToElements",
    "ariaHasPopup",
    "ariaHidden",
    "ariaInvalid",
    "ariaKeyShortcuts",
    "ariaLabel",
    "ariaLabelledByElements",
    "ariaLevel",
    "ariaLive",
    "ariaModal",
    "ariaMultiLine",
    "ariaMultiSelectable",
    "ariaNotify",
    "ariaOrientation",
    "ariaOwnsElements",
    "ariaPlaceholder",
    "ariaPosInSet",
    "ariaPressed",
    "ariaReadOnly",
    "ariaRelevant",
    "ariaRequired",
    "ariaRoleDescription",
    "ariaRowCount",
    "ariaRowIndex",
    "ariaRowIndexText",
    "ariaRowSpan",
    "ariaSelected",
    "ariaSetSize",
    "ariaSort",
    "ariaValueMax",
    "ariaValueMin",
    "ariaValueNow",
    "ariaValueText",
    "assignedSlot",
    "attachInternals",
    "attachShadow",
    "attributeStyleMap",
    "attributes",
    "autocapitalize",
    "autocorrect",
    "autofocus",
    "baseURI",
    "before",
    "blur",
    "checkVisibility",
    "childElementCount",
    "childNodes",
    "children",
    "classList",
    "className",
    "click",
    "clientHeight",
    "clientLeft",
    "clientTop",
    "clientWidth",
    "cloneNode",
    "closest",
    "compareDocumentPosition",
    "computedStyleMap",
    "contains",
    "contentEditable",
    "cue",
    "cuebackground",
    "currentCSSZoom",
    "customElementRegistry",
    "dataset",
    "dir",
    "dispatchEvent",
    "draggable",
    "editContext",
    "elementTiming",
    "enterKeyHint",
    "firstChild",
    "firstElementChild",
    "focus",
    "focusGroup",
    "focusGroupStart",
    "getAnimations",
    "getAttribute",
    "getAttributeNS",
    "getAttributeNames",
    "getAttributeNode",
    "getAttributeNodeNS",
    "getBoundingClientRect",
    "getClientRects",
    "getElementsByClassName",
    "getElementsByTagName",
    "getElementsByTagNameNS",
    "getHTML",
    "getRootNode",
    "hasAttribute",
    "hasAttributeNS",
    "hasAttributes",
    "hasChildNodes",
    "hasPointerCapture",
    "headingOffset",
    "headingReset",
    "hidden",
    "hidePopover",
    "id",
    "inert",
    "innerHTML",
    "innerText",
    "inputMode",
    "insertAdjacentElement",
    "insertAdjacentHTML",
    "insertAdjacentText",
    "insertBefore",
    "isConnected",
    "isContentEditable",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lang",
    "lastChild",
    "lastElementChild",
    "localName",
    "lookupNamespaceURI",
    "lookupPrefix",
    "matches",
    "moveBefore",
    "mozMatchesSelector",
    "mozRequestFullScreen",
    "namespaceURI",
    "nextElementSibling",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "nonce",
    "normalize",
    "offsetHeight",
    "offsetLeft",
    "offsetParent",
    "offsetTop",
    "offsetWidth",
    "outerHTML",
    "outerText",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "part",
    "popover",
    "prefix",
    "prepend",
    "previousElementSibling",
    "previousSibling",
    "pseudo",
    "querySelector",
    "querySelectorAll",
    "releaseCapture",
    "releasePointerCapture",
    "remove",
    "removeAttribute",
    "removeAttributeNS",
    "removeAttributeNode",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "replaceWith",
    "requestFullscreen",
    "requestPointerLock",
    "role",
    "scroll",
    "scrollBy",
    "scrollHeight",
    "scrollIntoView",
    "scrollIntoViewIfNeeded",
    "scrollLeft",
    "scrollLeftMax",
    "scrollTo",
    "scrollTop",
    "scrollTopMax",
    "scrollWidth",
    "setAttribute",
    "setAttributeNS",
    "setAttributeNode",
    "setAttributeNodeNS",
    "setCapture",
    "setHTML",
    "setHTMLUnsafe",
    "setPointerCapture",
    "shadowRoot",
    "showPopover",
    "slot",
    "spellcheck",
    "startViewTransition",
    "style",
    "tabIndex",
    "tagName",
    "textContent",
    "title",
    "toggleAttribute",
    "togglePopover",
    "translate",
    "virtualKeyboardPolicy",
    "webkitMatchesSelector",
    "webkitRequestFullScreen",
    "webkitRequestFullscreen",
    "webkitdropzone",
    "when",
    "writingSuggestions"
  ],
  "shadowRoot": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "activeElement",
    "addEventListener",
    "adoptedStyleSheets",
    "append",
    "appendChild",
    "baseURI",
    "childElementCount",
    "childNodes",
    "children",
    "clonable",
    "cloneNode",
    "compareDocumentPosition",
    "contains",
    "customElementRegistry",
    "delegatesFocus",
    "dispatchEvent",
    "elementFromPoint",
    "elementsFromPoint",
    "firstChild",
    "firstElementChild",
    "fullscreenElement",
    "getAnimations",
    "getElementById",
    "getHTML",
    "getRootNode",
    "getSelection",
    "hasChildNodes",
    "host",
    "innerHTML",
    "insertBefore",
    "isConnected",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lastChild",
    "lastElementChild",
    "lookupNamespaceURI",
    "lookupPrefix",
    "mode",
    "moveBefore",
    "mozFullScreenElement",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "normalize",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "pictureInPictureElement",
    "pointerLockElement",
    "prepend",
    "previousSibling",
    "querySelector",
    "querySelectorAll",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "serializable",
    "setHTML",
    "setHTMLUnsafe",
    "slotAssignment",
    "styleSheets",
    "textContent",
    "when"
  ],
  "document": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "URL",
    "activeElement",
    "activeViewTransition",
    "addEventListener",
    "adoptNode",
    "adoptedStyleSheets",
    "alinkColor",
    "all",
    "anchors",
    "append",
    "appendChild",
    "applets",
    "ariaNotify",
    "baseURI",
    "bgColor",
    "body",
    "browsingTopics",
    "captureEvents",
    "caretPositionFromPoint",
    "caretRangeFromPoint",
    "characterSet",
    "charset",
    "childElementCount",
    "childNodes",
    "children",
    "clear",
    "cloneNode",
    "close",
    "compareDocumentPosition",
    "compatMode",
    "contains",
    "contentType",
    "cookie",
    "createAttribute",
    "createAttributeNS",
    "createCDATASection",
    "createComment",
    "createDocumentFragment",
    "createElement",
    "createElementNS",
    "createEvent",
    "createExpression",
    "createNSResolver",
    "createNodeIterator",
    "createProcessingInstruction",
    "createRange",
    "createTextNode",
    "createTouch",
    "createTouchList",
    "createTreeWalker",
    "currentScript",
    "customElementRegistry",
    "defaultView",
    "designMode",
    "dir",
    "dispatchEvent",
    "doctype",
    "documentElement",
    "documentURI",
    "domain",
    "elementFromPoint",
    "elementsFromPoint",
    "embeds",
    "enableStyleSheetsForSet",
    "evaluate",
    "execCommand",
    "exitFullscreen",
    "exitPictureInPicture",
    "exitPointerLock",
    "featurePolicy",
    "fgColor",
    "firstChild",
    "firstElementChild",
    "fonts",
    "forms",
    "fragmentDirective",
    "fullscreen",
    "fullscreenElement",
    "fullscreenEnabled",
    "getAnimations",
    "getCSSCanvasContext",
    "getElementById",
    "getElementsByClassName",
    "getElementsByName",
    "getElementsByTagName",
    "getElementsByTagNameNS",
    "getRootNode",
    "getSelection",
    "hasChildNodes",
    "hasFocus",
    "hasPrivateToken",
    "hasRedemptionRecord",
    "hasStorageAccess",
    "hasUnpartitionedCookieAccess",
    "head",
    "hidden",
    "images",
    "implementation",
    "importNode",
    "inputEncoding",
    "insertBefore",
    "isConnected",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lastChild",
    "lastElementChild",
    "lastModified",
    "lastStyleSheetSet",
    "linkColor",
    "links",
    "lookupNamespaceURI",
    "lookupPrefix",
    "moveBefore",
    "mozCancelFullScreen",
    "mozFullScreen",
    "mozFullScreenElement",
    "mozFullScreenEnabled",
    "mozSetImageElement",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "normalize",
    "open",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "pictureInPictureElement",
    "pictureInPictureEnabled",
    "plugins",
    "pointerLockElement",
    "preferredStyleSheetSet",
    "prepend",
    "prerendering",
    "previousSibling",
    "queryCommandEnabled",
    "queryCommandIndeterm",
    "queryCommandState",
    "queryCommandSupported",
    "queryCommandValue",
    "querySelector",
    "querySelectorAll",
    "readyState",
    "referrer",
    "releaseCapture",
    "releaseEvents",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "requestStorageAccess",
    "requestStorageAccessFor",
    "rootElement",
    "scripts",
    "scrollingElement",
    "selectedStyleSheetSet",
    "startViewTransition",
    "styleSheetSets",
    "styleSheets",
    "textContent",
    "timeline",
    "title",
    "visibilityState",
    "vlinkColor",
    "wasDiscarded",
    "webkitCancelFullScreen",
    "webkitCurrentFullScreenElement",
    "webkitExitFullscreen",
    "webkitFullScreenKeyboardInputAllowed",
    "webkitFullscreenElement",
    "webkitFullscreenEnabled",
    "webkitHidden",
    "webkitIsFullScreen",
    "webkitVisibilityState",
    "when",
    "write",
    "writeln",
    "xmlEncoding",
    "xmlStandalone",
    "xmlVersion"
  ],
  "sheet": [
    "addRule",
    "cssRules",
    "deleteRule",
    "insertRule",
    "ownerRule",
    "removeRule",
    "replace",
    "replaceSync",
    "rules"
  ],
  "tokenList": [
    "add",
    "contains",
    "entries",
    "forEach",
    "item",
    "keys",
    "length",
    "remove",
    "replace",
    "supports",
    "toString",
    "toggle",
    "value",
    "values"
  ]
};

/** Kept for the browser guard, which only checks the element. */
export const SURFACE = SURFACES.element;

/**
 * Members the shim deliberately does not have, and why.
 *
 * A stub that returns a plausible value is worse than one that is absent: `dispatchEvent: () => true`
 * passed every test written against it for as long as nobody asked what `true` meant. Anything that
 * cannot be answered honestly by a detached element holding a string is listed here instead.
 */
/**
 * The globals a component reaches for, and what a server can honestly give it.
 *
 * `true` means the shim provides it. A string is the reason it is deliberately **absent** — and
 * absent is a real answer here, not an oversight: a component that reads `localStorage` on a server
 * is reading state that belongs to one browser, and inventing an empty one renders a logged-out
 * shell the client immediately replaces. `typeof localStorage === 'undefined'` is the guard the
 * whole ecosystem already writes, and it only works if we do not lie.
 */
export const GLOBALS = {
  HTMLElement: true,
  Element: true,
  Node: true,
  ShadowRoot: true,
  DocumentFragment: true,
  Image: true,
  Audio: true,
  CSSStyleSheet: true,
  CSSScopeRule: true,
  Event: true,
  CustomEvent: true,
  EventTarget: true,
  customElements: true,
  document: true,
  window: true,
  location: true,
  history: true,
  navigator: true,
  requestAnimationFrame: true,
  cancelAnimationFrame: true,
  requestIdleCallback: true,
  cancelIdleCallback: true,
  matchMedia: true,
  getComputedStyle: true,
  getSelection: true,
  scrollTo: true,
  /** The other name for the global. `window` is defined, so a UMD bundle has already taken the browser branch. */
  self: true,
  addEventListener: true,
  removeEventListener: true,
  dispatchEvent: true,
  IntersectionObserver: true,
  ResizeObserver: true,
  MutationObserver: true,
  PerformanceObserver: true,

  /**
   * **The viewport family is absent on purpose, and the reason is not the same as `localStorage`'s.**
   * Nobody writes `typeof innerWidth === 'undefined'`, so the guard argument does not carry here.
   * What carries is consistency with `matchMedia`, which is *provided* and matches nothing: that is
   * the server saying "no media query applies", which renders the base shell. An `innerWidth` of `0`
   * would have the component beside it conclude it is on a zero-width phone and render the mobile
   * shell instead — two answers to the same question, from the same render. Absent, the read is a
   * `TypeError` the author fixes; present and zero, it is a wrong shell nobody sees until hydration
   * replaces it.
   */
  localStorage: 'per-user state a server must not invent; guard with typeof',
  sessionStorage: 'per-user state a server must not invent; guard with typeof',
  indexedDB: 'per-user state a server must not invent; guard with typeof',
  caches: 'per-user state a server must not invent; guard with typeof',
  DOMParser: 'parses HTML into a tree; nothing in this package parses HTML',
  XMLSerializer: 'serializes a tree; the markup is built as a string',
  Range: 'needs a tree',
  Selection: 'needs a tree and a user',
  alert: 'needs a user',
  confirm: 'needs a user',
  prompt: 'needs a user',
  open: 'needs a browsing context',
  print: 'needs a browsing context',
  screen: 'needs a display',
  visualViewport: 'needs a viewport',
  devicePixelRatio: 'needs a display',
  innerWidth: 'needs a viewport',
  innerHeight: 'needs a viewport',
  scrollX: 'needs a viewport',
  scrollY: 'needs a viewport',
};

export const OUT_OF_SCOPE = {
  "tokenList": {},
  "element": {
    "insertBefore": "needs a tree; this DOM holds children as a string",
    "moveBefore": "needs a tree",
    "removeChild": "needs a tree",
    "replaceChild": "needs a tree",
    "cloneNode": "needs a tree, and a copy that shared the string would alias it",
    "after": "places content beside this element, which needs the parent it has none of",
    "before": "places content beside this element, which needs the parent it has none of",
    "replaceWith": "places content beside this element, which needs the parent it has none of",
    "compareDocumentPosition": "compares positions in a tree",
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "customElementRegistry": "scoped registries; there is one registry here",
    "animate": "needs a compositor",
    "getAnimations": "needs a compositor",
    "startViewTransition": "needs a compositor",
    "activeViewTransition": "needs a compositor",
    "requestFullscreen": "needs a viewport and a user gesture",
    "webkitRequestFullscreen": "needs a viewport and a user gesture",
    "webkitRequestFullScreen": "needs a viewport and a user gesture",
    "mozRequestFullScreen": "needs a viewport and a user gesture",
    "requestPointerLock": "needs a viewport and a user gesture",
    "setPointerCapture": "needs a pointer",
    "releasePointerCapture": "needs a pointer",
    "hasPointerCapture": "needs a pointer",
    "setCapture": "needs a pointer",
    "releaseCapture": "needs a pointer",
    "scrollIntoViewIfNeeded": "needs layout; the standard scrollIntoView is a no-op here",
    "attributeStyleMap": "Typed OM; the string style view is what the markup carries",
    "computedStyleMap": "Typed OM, and there is no computed style without layout",
    "editContext": "needs an input method",
    "getHTML": "serializes shadow roots on demand; the SSR pipeline already decides that",
    "setHTML": "needs the Sanitizer API",
    "setHTMLUnsafe": "declarative shadow roots in a fragment; renderToString owns that decision",
    "outerText": "proprietary; innerText covers the reachable case",
    "accessKeyLabel": "derived from the platform keyboard",
    "pseudo": "set by the engine for pseudo-elements",
    "cue": "proprietary",
    "cuebackground": "proprietary",
    "webkitdropzone": "proprietary",
    "ariaNotify": "experimental, announces to a screen reader",
    "when": "experimental",
    "elementTiming": "reflects to an attribute only a performance observer reads",
    "focusGroup": "experimental",
    "focusGroupStart": "experimental",
    "headingOffset": "experimental",
    "headingReset": "experimental",
    "showPopover": "needs a top layer",
    "hidePopover": "needs a top layer",
    "togglePopover": "needs a top layer",
    "ariaActionsElements": "an element reference, not an attribute",
    "ariaActiveDescendantElement": "an element reference, not an attribute",
    "ariaControlsElements": "an element reference, not an attribute",
    "ariaDescribedByElements": "an element reference, not an attribute",
    "ariaDetailsElements": "an element reference, not an attribute",
    "ariaErrorMessageElements": "an element reference, not an attribute",
    "ariaFlowToElements": "an element reference, not an attribute",
    "ariaLabelledByElements": "an element reference, not an attribute",
    "ariaOwnsElements": "an element reference, not an attribute"
  },
  "shadowRoot": {
    "insertBefore": "needs a tree; this DOM holds children as a string",
    "removeChild": "needs a tree; this DOM holds children as a string",
    "replaceChild": "needs a tree; this DOM holds children as a string",
    "moveBefore": "needs a tree; this DOM holds children as a string",
    "cloneNode": "needs a tree; this DOM holds children as a string",
    "compareDocumentPosition": "needs a tree; this DOM holds children as a string",
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "getAnimations": "needs a compositor",
    "when": "needs a compositor",
    "customElementRegistry": "scoped registries; there is one registry here",
    "getHTML": "serializes shadow roots on demand; renderToString owns that decision",
    "setHTML": "serializes shadow roots on demand; renderToString owns that decision",
    "setHTMLUnsafe": "serializes shadow roots on demand; renderToString owns that decision",
    "mozFullScreenElement": "engine-proprietary fullscreen"
  },
  "document": {
    "append": "needs a tree; this DOM holds children as a string",
    "appendChild": "needs a tree; this DOM holds children as a string",
    "prepend": "needs a tree; this DOM holds children as a string",
    "replaceChildren": "needs a tree; this DOM holds children as a string",
    "insertBefore": "needs a tree; this DOM holds children as a string",
    "removeChild": "needs a tree; this DOM holds children as a string",
    "replaceChild": "needs a tree; this DOM holds children as a string",
    "moveBefore": "needs a tree; this DOM holds children as a string",
    "cloneNode": "needs a tree; this DOM holds children as a string",
    "compareDocumentPosition": "needs a tree; this DOM holds children as a string",
    "firstChild": "needs a tree; this DOM holds children as a string",
    "lastChild": "needs a tree; this DOM holds children as a string",
    "nextSibling": "needs a tree; this DOM holds children as a string",
    "previousSibling": "needs a tree; this DOM holds children as a string",
    "parentNode": "needs a tree; this DOM holds children as a string",
    "parentElement": "needs a tree; this DOM holds children as a string",
    "normalize": "needs a tree; this DOM holds children as a string",
    "isSameNode": "needs a tree; this DOM holds children as a string",
    "isEqualNode": "needs a tree; this DOM holds children as a string",
    "hasChildNodes": "needs a tree; this DOM holds children as a string",
    "textContent": "needs a tree; this DOM holds children as a string",
    "nodeValue": "needs a tree; this DOM holds children as a string",
    "getRootNode": "needs a tree; this DOM holds children as a string",
    "isConnected": "needs a tree; this DOM holds children as a string",
    "ownerDocument": "needs a tree; this DOM holds children as a string",
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "createNSResolver": "needs a document to resolve namespaces against",
    "createExpression": "needs a document to resolve namespaces against",
    "evaluate": "needs a document to resolve namespaces against",
    "createAttribute": "node kinds this serializer does not emit",
    "createAttributeNS": "node kinds this serializer does not emit",
    "createCDATASection": "node kinds this serializer does not emit",
    "createProcessingInstruction": "node kinds this serializer does not emit",
  "createRange": "needs a tree, and a null stub would fail later and worse than an absent method",
          "createEvent": "node kinds this serializer does not emit",
    "createTouch": "node kinds this serializer does not emit",
    "createTouchList": "node kinds this serializer does not emit",
    "implementation": "node kinds this serializer does not emit",
    "rootElement": "node kinds this serializer does not emit",
    "xmlEncoding": "node kinds this serializer does not emit",
    "xmlStandalone": "node kinds this serializer does not emit",
    "xmlVersion": "node kinds this serializer does not emit",
    "fragmentDirective": "node kinds this serializer does not emit",
    "open": "document.open/write build a document by parsing; nothing here parses HTML",
    "close": "document.open/write build a document by parsing; nothing here parses HTML",
    "write": "document.open/write build a document by parsing; nothing here parses HTML",
    "writeln": "document.open/write build a document by parsing; nothing here parses HTML",
    "clear": "document.open/write build a document by parsing; nothing here parses HTML",
    "all": "document.open/write build a document by parsing; nothing here parses HTML",
    "captureEvents": "document.open/write build a document by parsing; nothing here parses HTML",
    "releaseEvents": "document.open/write build a document by parsing; nothing here parses HTML",
    "releaseCapture": "document.open/write build a document by parsing; nothing here parses HTML",
    "alinkColor": "legacy presentational attributes of <body>",
    "bgColor": "legacy presentational attributes of <body>",
    "fgColor": "legacy presentational attributes of <body>",
    "linkColor": "legacy presentational attributes of <body>",
    "vlinkColor": "legacy presentational attributes of <body>",
    "applets": "legacy presentational attributes of <body>",
    "domain": "legacy presentational attributes of <body>",
    "lastModified": "legacy presentational attributes of <body>",
    "wasDiscarded": "legacy presentational attributes of <body>",
    "prerendering": "legacy presentational attributes of <body>",
    "execCommand": "editing commands, which need a live selection",
    "queryCommandEnabled": "editing commands, which need a live selection",
    "queryCommandIndeterm": "editing commands, which need a live selection",
    "queryCommandState": "editing commands, which need a live selection",
    "queryCommandSupported": "editing commands, which need a live selection",
    "queryCommandValue": "editing commands, which need a live selection",
    "caretPositionFromPoint": "editing commands, which need a live selection",
    "caretRangeFromPoint": "editing commands, which need a live selection",
    "getCSSCanvasContext": "editing commands, which need a live selection",
    "mozSetImageElement": "editing commands, which need a live selection",
    "getAnimations": "needs a compositor",
    "startViewTransition": "needs a compositor",
    "activeViewTransition": "needs a compositor",
    "timeline": "needs a compositor",
    "fonts": "needs a compositor",
    "when": "needs a compositor",
    "ariaNotify": "needs a compositor",
    "exitFullscreen": "needs a viewport and a user gesture",
    "fullscreen": "needs a viewport and a user gesture",
    "fullscreenEnabled": "needs a viewport and a user gesture",
    "exitPictureInPicture": "needs a viewport and a user gesture",
    "pictureInPictureEnabled": "needs a viewport and a user gesture",
    "exitPointerLock": "needs a viewport and a user gesture",
    "mozCancelFullScreen": "needs a viewport and a user gesture",
    "mozFullScreen": "needs a viewport and a user gesture",
    "mozFullScreenElement": "needs a viewport and a user gesture",
    "mozFullScreenEnabled": "needs a viewport and a user gesture",
    "webkitCancelFullScreen": "needs a viewport and a user gesture",
    "webkitCurrentFullScreenElement": "needs a viewport and a user gesture",
    "webkitExitFullscreen": "needs a viewport and a user gesture",
    "webkitFullScreenKeyboardInputAllowed": "needs a viewport and a user gesture",
    "webkitFullscreenElement": "needs a viewport and a user gesture",
    "webkitFullscreenEnabled": "needs a viewport and a user gesture",
    "webkitIsFullScreen": "needs a viewport and a user gesture",
    "webkitHidden": "needs a viewport and a user gesture",
    "webkitVisibilityState": "needs a viewport and a user gesture",
    "enableStyleSheetsForSet": "needs a viewport and a user gesture",
    "lastStyleSheetSet": "needs a viewport and a user gesture",
    "preferredStyleSheetSet": "needs a viewport and a user gesture",
    "selectedStyleSheetSet": "needs a viewport and a user gesture",
    "styleSheetSets": "needs a viewport and a user gesture",
    "cookie": "per-user state a server must not invent",
    "hasStorageAccess": "per-user state a server must not invent",
    "requestStorageAccess": "per-user state a server must not invent",
    "requestStorageAccessFor": "per-user state a server must not invent",
    "hasPrivateToken": "per-user state a server must not invent",
    "hasRedemptionRecord": "per-user state a server must not invent",
    "hasUnpartitionedCookieAccess": "per-user state a server must not invent",
    "browsingTopics": "per-user state a server must not invent",
    "featurePolicy": "per-user state a server must not invent",
    "customElementRegistry": "scoped registries; there is one registry here",
    "getHTML": "serializes on demand; renderToString owns that decision",
    "setHTML": "serializes on demand; renderToString owns that decision",
    "setHTMLUnsafe": "serializes on demand; renderToString owns that decision"
  },
  "sheet": {}
};
