/**
 * The surface a real element exposes, taken from Chromium, Firefox and WebKit.
 *
 * `@verajs/ssr`'s server DOM was extended reactively for its whole life: every missing member was
 * found by someone tripping over it, one at a time. This is the list it is held to, so a gap fails a
 * test instead of a render. It is data, not code — no dependency parses or derives it.
 *
 * **Regenerating:** `tests/browser/dom-surface.test.js` fails when an engine exposes something not
 * listed here, and prints the names. Add each one either to the shim or to `OUT_OF_SCOPE` with the
 * reason it cannot work on a server.
 *
 * `on*` event handlers are excluded — there are hundreds, and none of them reach markup.
 */
export const SURFACE = [
  "ATTRIBUTE_NODE",
  "CDATA_SECTION_NODE",
  "COMMENT_NODE",
  "DOCUMENT_FRAGMENT_NODE",
  "DOCUMENT_NODE",
  "DOCUMENT_POSITION_CONTAINED_BY",
  "DOCUMENT_POSITION_CONTAINS",
  "DOCUMENT_POSITION_DISCONNECTED",
  "DOCUMENT_POSITION_FOLLOWING",
  "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
  "DOCUMENT_POSITION_PRECEDING",
  "DOCUMENT_TYPE_NODE",
  "ELEMENT_NODE",
  "ENTITY_NODE",
  "ENTITY_REFERENCE_NODE",
  "NOTATION_NODE",
  "PROCESSING_INSTRUCTION_NODE",
  "TEXT_NODE",
  "accessKey",
  "accessKeyLabel",
  "activeViewTransition",
  "addEventListener",
  "after",
  "animate",
  "append",
  "appendChild",
  "ariaActionsElements",
  "ariaActiveDescendantElement",
  "ariaAtomic",
  "ariaAutoComplete",
  "ariaBrailleLabel",
  "ariaBrailleRoleDescription",
  "ariaBusy",
  "ariaChecked",
  "ariaColCount",
  "ariaColIndex",
  "ariaColIndexText",
  "ariaColSpan",
  "ariaControlsElements",
  "ariaCurrent",
  "ariaDescribedByElements",
  "ariaDescription",
  "ariaDetailsElements",
  "ariaDisabled",
  "ariaErrorMessageElements",
  "ariaExpanded",
  "ariaFlowToElements",
  "ariaHasPopup",
  "ariaHidden",
  "ariaInvalid",
  "ariaKeyShortcuts",
  "ariaLabel",
  "ariaLabelledByElements",
  "ariaLevel",
  "ariaLive",
  "ariaModal",
  "ariaMultiLine",
  "ariaMultiSelectable",
  "ariaNotify",
  "ariaOrientation",
  "ariaOwnsElements",
  "ariaPlaceholder",
  "ariaPosInSet",
  "ariaPressed",
  "ariaReadOnly",
  "ariaRelevant",
  "ariaRequired",
  "ariaRoleDescription",
  "ariaRowCount",
  "ariaRowIndex",
  "ariaRowIndexText",
  "ariaRowSpan",
  "ariaSelected",
  "ariaSetSize",
  "ariaSort",
  "ariaValueMax",
  "ariaValueMin",
  "ariaValueNow",
  "ariaValueText",
  "assignedSlot",
  "attachInternals",
  "attachShadow",
  "attributeStyleMap",
  "attributes",
  "autocapitalize",
  "autocorrect",
  "autofocus",
  "baseURI",
  "before",
  "blur",
  "checkVisibility",
  "childElementCount",
  "childNodes",
  "children",
  "classList",
  "className",
  "click",
  "clientHeight",
  "clientLeft",
  "clientTop",
  "clientWidth",
  "cloneNode",
  "closest",
  "compareDocumentPosition",
  "computedStyleMap",
  "contains",
  "contentEditable",
  "cue",
  "cuebackground",
  "currentCSSZoom",
  "customElementRegistry",
  "dataset",
  "dir",
  "dispatchEvent",
  "draggable",
  "editContext",
  "elementTiming",
  "enterKeyHint",
  "firstChild",
  "firstElementChild",
  "focus",
  "focusGroup",
  "focusGroupStart",
  "getAnimations",
  "getAttribute",
  "getAttributeNS",
  "getAttributeNames",
  "getAttributeNode",
  "getAttributeNodeNS",
  "getBoundingClientRect",
  "getClientRects",
  "getElementsByClassName",
  "getElementsByTagName",
  "getElementsByTagNameNS",
  "getHTML",
  "getRootNode",
  "hasAttribute",
  "hasAttributeNS",
  "hasAttributes",
  "hasChildNodes",
  "hasPointerCapture",
  "headingOffset",
  "headingReset",
  "hidden",
  "hidePopover",
  "id",
  "inert",
  "innerHTML",
  "innerText",
  "inputMode",
  "insertAdjacentElement",
  "insertAdjacentHTML",
  "insertAdjacentText",
  "insertBefore",
  "isConnected",
  "isContentEditable",
  "isDefaultNamespace",
  "isEqualNode",
  "isSameNode",
  "lang",
  "lastChild",
  "lastElementChild",
  "localName",
  "lookupNamespaceURI",
  "lookupPrefix",
  "matches",
  "moveBefore",
  "mozMatchesSelector",
  "mozRequestFullScreen",
  "namespaceURI",
  "nextElementSibling",
  "nextSibling",
  "nodeName",
  "nodeType",
  "nodeValue",
  "nonce",
  "normalize",
  "offsetHeight",
  "offsetLeft",
  "offsetParent",
  "offsetTop",
  "offsetWidth",
  "outerHTML",
  "outerText",
  "ownerDocument",
  "parentElement",
  "parentNode",
  "part",
  "popover",
  "prefix",
  "prepend",
  "previousElementSibling",
  "previousSibling",
  "pseudo",
  "querySelector",
  "querySelectorAll",
  "releaseCapture",
  "releasePointerCapture",
  "remove",
  "removeAttribute",
  "removeAttributeNS",
  "removeAttributeNode",
  "removeChild",
  "removeEventListener",
  "replaceChild",
  "replaceChildren",
  "replaceWith",
  "requestFullscreen",
  "requestPointerLock",
  "role",
  "scroll",
  "scrollBy",
  "scrollHeight",
  "scrollIntoView",
  "scrollIntoViewIfNeeded",
  "scrollLeft",
  "scrollLeftMax",
  "scrollTo",
  "scrollTop",
  "scrollTopMax",
  "scrollWidth",
  "setAttribute",
  "setAttributeNS",
  "setAttributeNode",
  "setAttributeNodeNS",
  "setCapture",
  "setHTML",
  "setHTMLUnsafe",
  "setPointerCapture",
  "shadowRoot",
  "showPopover",
  "slot",
  "spellcheck",
  "startViewTransition",
  "style",
  "tabIndex",
  "tagName",
  "textContent",
  "title",
  "toggleAttribute",
  "togglePopover",
  "translate",
  "virtualKeyboardPolicy",
  "webkitMatchesSelector",
  "webkitRequestFullScreen",
  "webkitRequestFullscreen",
  "webkitdropzone",
  "when",
  "writingSuggestions"
];

/**
 * Members the shim deliberately does not have, and why.
 *
 * A stub that returns a plausible value is worse than one that is absent: `dispatchEvent: () => true`
 * passed every test written against it for as long as nobody asked what `true` meant. Anything that
 * cannot be answered honestly by a detached element holding a string is listed here instead.
 */
export const OUT_OF_SCOPE = {
  "insertBefore": "needs a tree; this DOM holds children as a string",
  "moveBefore": "needs a tree",
  "removeChild": "needs a tree",
  "replaceChild": "needs a tree",
  "cloneNode": "needs a tree, and a copy that shared the string would alias it",
  "after": "places content beside this element, which needs the parent it has none of",
  "before": "places content beside this element, which needs the parent it has none of",
  "replaceWith": "places content beside this element, which needs the parent it has none of",
  "compareDocumentPosition": "compares positions in a tree",
  "isDefaultNamespace": "needs a document to resolve namespaces against",
  "lookupNamespaceURI": "needs a document to resolve namespaces against",
  "lookupPrefix": "needs a document to resolve namespaces against",
  "customElementRegistry": "scoped registries; there is one registry here",
  "animate": "needs a compositor",
  "getAnimations": "needs a compositor",
  "startViewTransition": "needs a compositor",
  "activeViewTransition": "needs a compositor",
  "requestFullscreen": "needs a viewport and a user gesture",
  "webkitRequestFullscreen": "needs a viewport and a user gesture",
  "webkitRequestFullScreen": "needs a viewport and a user gesture",
  "mozRequestFullScreen": "needs a viewport and a user gesture",
  "requestPointerLock": "needs a viewport and a user gesture",
  "setPointerCapture": "needs a pointer",
  "releasePointerCapture": "needs a pointer",
  "hasPointerCapture": "needs a pointer",
  "setCapture": "needs a pointer",
  "releaseCapture": "needs a pointer",
  "scrollIntoViewIfNeeded": "needs layout; the standard scrollIntoView is a no-op here",
  "attributeStyleMap": "Typed OM; the string style view is what the markup carries",
  "computedStyleMap": "Typed OM, and there is no computed style without layout",
  "editContext": "needs an input method",
  "getHTML": "serializes shadow roots on demand; the SSR pipeline already decides that",
  "setHTML": "needs the Sanitizer API",
  "setHTMLUnsafe": "declarative shadow roots in a fragment; renderToString owns that decision",
  "outerText": "proprietary; innerText covers the reachable case",
  "accessKeyLabel": "derived from the platform keyboard",
  "pseudo": "set by the engine for pseudo-elements",
  "cue": "proprietary",
  "cuebackground": "proprietary",
  "webkitdropzone": "proprietary",
  "ariaNotify": "experimental, announces to a screen reader",
  "when": "experimental",
  "elementTiming": "reflects to an attribute only a performance observer reads",
  "focusGroup": "experimental",
  "focusGroupStart": "experimental",
  "headingOffset": "experimental",
  "headingReset": "experimental",
  "showPopover": "needs a top layer",
  "hidePopover": "needs a top layer",
  "togglePopover": "needs a top layer",
  "ariaActionsElements": "an element reference, not an attribute",
  "ariaActiveDescendantElement": "an element reference, not an attribute",
  "ariaControlsElements": "an element reference, not an attribute",
  "ariaDescribedByElements": "an element reference, not an attribute",
  "ariaDetailsElements": "an element reference, not an attribute",
  "ariaErrorMessageElements": "an element reference, not an attribute",
  "ariaFlowToElements": "an element reference, not an attribute",
  "ariaLabelledByElements": "an element reference, not an attribute",
  "ariaOwnsElements": "an element reference, not an attribute"
};
