/**
 * The surface a real element, shadow root, document and stylesheet expose, taken from Chromium, Firefox and WebKit.
 *
 * `@verajs/ssr`'s server DOM was extended reactively for its whole life: every missing member was
 * found by someone tripping over it, one at a time. This is the list it is held to, so a gap fails a
 * test instead of a render. It is data, not code — no dependency parses or derives it.
 *
 * **Regenerating:** `tests/browser/dom-surface.test.js` fails when an engine exposes something not
 * listed here, and prints the names. Add each one either to the shim or to `OUT_OF_SCOPE` with the
 * reason it cannot work on a server.
 *
 * `on*` event handlers are excluded — there are hundreds, and none of them reach markup.
 */
export const SURFACES = {
  "element": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "accessKey",
    "accessKeyLabel",
    "activeViewTransition",
    "addEventListener",
    "after",
    "animate",
    "append",
    "appendChild",
    "ariaActionsElements",
    "ariaActiveDescendantElement",
    "ariaAtomic",
    "ariaAutoComplete",
    "ariaBrailleLabel",
    "ariaBrailleRoleDescription",
    "ariaBusy",
    "ariaChecked",
    "ariaColCount",
    "ariaColIndex",
    "ariaColIndexText",
    "ariaColSpan",
    "ariaControlsElements",
    "ariaCurrent",
    "ariaDescribedByElements",
    "ariaDescription",
    "ariaDetailsElements",
    "ariaDisabled",
    "ariaErrorMessageElements",
    "ariaExpanded",
    "ariaFlowToElements",
    "ariaHasPopup",
    "ariaHidden",
    "ariaInvalid",
    "ariaKeyShortcuts",
    "ariaLabel",
    "ariaLabelledByElements",
    "ariaLevel",
    "ariaLive",
    "ariaModal",
    "ariaMultiLine",
    "ariaMultiSelectable",
    "ariaNotify",
    "ariaOrientation",
    "ariaOwnsElements",
    "ariaPlaceholder",
    "ariaPosInSet",
    "ariaPressed",
    "ariaReadOnly",
    "ariaRelevant",
    "ariaRequired",
    "ariaRoleDescription",
    "ariaRowCount",
    "ariaRowIndex",
    "ariaRowIndexText",
    "ariaRowSpan",
    "ariaSelected",
    "ariaSetSize",
    "ariaSort",
    "ariaValueMax",
    "ariaValueMin",
    "ariaValueNow",
    "ariaValueText",
    "assignedSlot",
    "attachInternals",
    "attachShadow",
    "attributeStyleMap",
    "attributes",
    "autocapitalize",
    "autocorrect",
    "autofocus",
    "baseURI",
    "before",
    "blur",
    "checkVisibility",
    "childElementCount",
    "childNodes",
    "children",
    "classList",
    "className",
    "click",
    "clientHeight",
    "clientLeft",
    "clientTop",
    "clientWidth",
    "cloneNode",
    "closest",
    "compareDocumentPosition",
    "computedStyleMap",
    "contains",
    "contentEditable",
    "cue",
    "cuebackground",
    "currentCSSZoom",
    "customElementRegistry",
    "dataset",
    "dir",
    "dispatchEvent",
    "draggable",
    "editContext",
    "elementTiming",
    "enterKeyHint",
    "firstChild",
    "firstElementChild",
    "focus",
    "focusGroup",
    "focusGroupStart",
    "getAnimations",
    "getAttribute",
    "getAttributeNS",
    "getAttributeNames",
    "getAttributeNode",
    "getAttributeNodeNS",
    "getBoundingClientRect",
    "getClientRects",
    "getElementsByClassName",
    "getElementsByTagName",
    "getElementsByTagNameNS",
    "getHTML",
    "getRootNode",
    "hasAttribute",
    "hasAttributeNS",
    "hasAttributes",
    "hasChildNodes",
    "hasPointerCapture",
    "headingOffset",
    "headingReset",
    "hidden",
    "hidePopover",
    "id",
    "inert",
    "innerHTML",
    "innerText",
    "inputMode",
    "insertAdjacentElement",
    "insertAdjacentHTML",
    "insertAdjacentText",
    "insertBefore",
    "isConnected",
    "isContentEditable",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lang",
    "lastChild",
    "lastElementChild",
    "localName",
    "lookupNamespaceURI",
    "lookupPrefix",
    "matches",
    "moveBefore",
    "mozMatchesSelector",
    "mozRequestFullScreen",
    "namespaceURI",
    "nextElementSibling",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "nonce",
    "normalize",
    "offsetHeight",
    "offsetLeft",
    "offsetParent",
    "offsetTop",
    "offsetWidth",
    "outerHTML",
    "outerText",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "part",
    "popover",
    "prefix",
    "prepend",
    "previousElementSibling",
    "previousSibling",
    "pseudo",
    "querySelector",
    "querySelectorAll",
    "releaseCapture",
    "releasePointerCapture",
    "remove",
    "removeAttribute",
    "removeAttributeNS",
    "removeAttributeNode",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "replaceWith",
    "requestFullscreen",
    "requestPointerLock",
    "role",
    "scroll",
    "scrollBy",
    "scrollHeight",
    "scrollIntoView",
    "scrollIntoViewIfNeeded",
    "scrollLeft",
    "scrollLeftMax",
    "scrollTo",
    "scrollTop",
    "scrollTopMax",
    "scrollWidth",
    "setAttribute",
    "setAttributeNS",
    "setAttributeNode",
    "setAttributeNodeNS",
    "setCapture",
    "setHTML",
    "setHTMLUnsafe",
    "setPointerCapture",
    "shadowRoot",
    "showPopover",
    "slot",
    "spellcheck",
    "startViewTransition",
    "style",
    "tabIndex",
    "tagName",
    "textContent",
    "title",
    "toggleAttribute",
    "togglePopover",
    "translate",
    "virtualKeyboardPolicy",
    "webkitMatchesSelector",
    "webkitRequestFullScreen",
    "webkitRequestFullscreen",
    "webkitdropzone",
    "when",
    "writingSuggestions"
  ],
  "shadowRoot": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "activeElement",
    "addEventListener",
    "adoptedStyleSheets",
    "append",
    "appendChild",
    "baseURI",
    "childElementCount",
    "childNodes",
    "children",
    "clonable",
    "cloneNode",
    "compareDocumentPosition",
    "contains",
    "customElementRegistry",
    "delegatesFocus",
    "dispatchEvent",
    "elementFromPoint",
    "elementsFromPoint",
    "firstChild",
    "firstElementChild",
    "fullscreenElement",
    "getAnimations",
    "getElementById",
    "getHTML",
    "getRootNode",
    "getSelection",
    "hasChildNodes",
    "host",
    "innerHTML",
    "insertBefore",
    "isConnected",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lastChild",
    "lastElementChild",
    "lookupNamespaceURI",
    "lookupPrefix",
    "mode",
    "moveBefore",
    "mozFullScreenElement",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "normalize",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "pictureInPictureElement",
    "pointerLockElement",
    "prepend",
    "previousSibling",
    "querySelector",
    "querySelectorAll",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "serializable",
    "setHTML",
    "setHTMLUnsafe",
    "slotAssignment",
    "styleSheets",
    "textContent",
    "when"
  ],
  "document": [
    "ATTRIBUTE_NODE",
    "CDATA_SECTION_NODE",
    "COMMENT_NODE",
    "DOCUMENT_FRAGMENT_NODE",
    "DOCUMENT_NODE",
    "DOCUMENT_POSITION_CONTAINED_BY",
    "DOCUMENT_POSITION_CONTAINS",
    "DOCUMENT_POSITION_DISCONNECTED",
    "DOCUMENT_POSITION_FOLLOWING",
    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC",
    "DOCUMENT_POSITION_PRECEDING",
    "DOCUMENT_TYPE_NODE",
    "ELEMENT_NODE",
    "ENTITY_NODE",
    "ENTITY_REFERENCE_NODE",
    "NOTATION_NODE",
    "PROCESSING_INSTRUCTION_NODE",
    "TEXT_NODE",
    "URL",
    "activeElement",
    "activeViewTransition",
    "addEventListener",
    "adoptNode",
    "adoptedStyleSheets",
    "alinkColor",
    "all",
    "anchors",
    "append",
    "appendChild",
    "applets",
    "ariaNotify",
    "baseURI",
    "bgColor",
    "body",
    "browsingTopics",
    "captureEvents",
    "caretPositionFromPoint",
    "caretRangeFromPoint",
    "characterSet",
    "charset",
    "childElementCount",
    "childNodes",
    "children",
    "clear",
    "cloneNode",
    "close",
    "compareDocumentPosition",
    "compatMode",
    "contains",
    "contentType",
    "cookie",
    "createAttribute",
    "createAttributeNS",
    "createCDATASection",
    "createComment",
    "createDocumentFragment",
    "createElement",
    "createElementNS",
    "createEvent",
    "createExpression",
    "createNSResolver",
    "createNodeIterator",
    "createProcessingInstruction",
    "createRange",
    "createTextNode",
    "createTouch",
    "createTouchList",
    "createTreeWalker",
    "currentScript",
    "customElementRegistry",
    "defaultView",
    "designMode",
    "dir",
    "dispatchEvent",
    "doctype",
    "documentElement",
    "documentURI",
    "domain",
    "elementFromPoint",
    "elementsFromPoint",
    "embeds",
    "enableStyleSheetsForSet",
    "evaluate",
    "execCommand",
    "exitFullscreen",
    "exitPictureInPicture",
    "exitPointerLock",
    "featurePolicy",
    "fgColor",
    "firstChild",
    "firstElementChild",
    "fonts",
    "forms",
    "fragmentDirective",
    "fullscreen",
    "fullscreenElement",
    "fullscreenEnabled",
    "getAnimations",
    "getCSSCanvasContext",
    "getElementById",
    "getElementsByClassName",
    "getElementsByName",
    "getElementsByTagName",
    "getElementsByTagNameNS",
    "getRootNode",
    "getSelection",
    "hasChildNodes",
    "hasFocus",
    "hasPrivateToken",
    "hasRedemptionRecord",
    "hasStorageAccess",
    "hasUnpartitionedCookieAccess",
    "head",
    "hidden",
    "images",
    "implementation",
    "importNode",
    "inputEncoding",
    "insertBefore",
    "isConnected",
    "isDefaultNamespace",
    "isEqualNode",
    "isSameNode",
    "lastChild",
    "lastElementChild",
    "lastModified",
    "lastStyleSheetSet",
    "linkColor",
    "links",
    "lookupNamespaceURI",
    "lookupPrefix",
    "moveBefore",
    "mozCancelFullScreen",
    "mozFullScreen",
    "mozFullScreenElement",
    "mozFullScreenEnabled",
    "mozSetImageElement",
    "nextSibling",
    "nodeName",
    "nodeType",
    "nodeValue",
    "normalize",
    "open",
    "ownerDocument",
    "parentElement",
    "parentNode",
    "pictureInPictureElement",
    "pictureInPictureEnabled",
    "plugins",
    "pointerLockElement",
    "preferredStyleSheetSet",
    "prepend",
    "prerendering",
    "previousSibling",
    "queryCommandEnabled",
    "queryCommandIndeterm",
    "queryCommandState",
    "queryCommandSupported",
    "queryCommandValue",
    "querySelector",
    "querySelectorAll",
    "readyState",
    "referrer",
    "releaseCapture",
    "releaseEvents",
    "removeChild",
    "removeEventListener",
    "replaceChild",
    "replaceChildren",
    "requestStorageAccess",
    "requestStorageAccessFor",
    "rootElement",
    "scripts",
    "scrollingElement",
    "selectedStyleSheetSet",
    "startViewTransition",
    "styleSheetSets",
    "styleSheets",
    "textContent",
    "timeline",
    "title",
    "visibilityState",
    "vlinkColor",
    "wasDiscarded",
    "webkitCancelFullScreen",
    "webkitCurrentFullScreenElement",
    "webkitExitFullscreen",
    "webkitFullScreenKeyboardInputAllowed",
    "webkitFullscreenElement",
    "webkitFullscreenEnabled",
    "webkitHidden",
    "webkitIsFullScreen",
    "webkitVisibilityState",
    "when",
    "write",
    "writeln",
    "xmlEncoding",
    "xmlStandalone",
    "xmlVersion"
  ],
  "sheet": [
    "addRule",
    "cssRules",
    "deleteRule",
    "insertRule",
    "ownerRule",
    "removeRule",
    "replace",
    "replaceSync",
    "rules"
  ],
  /**
   * **The window, minus its ~700 constructors.**
   *
   * `Window.prototype` is empty in every engine — the members live as own properties of the global
   * object — so this is `Object.getOwnPropertyNames(window)` with `on*` handlers and constructors
   * removed. The constructors are excluded on purpose and covered by a rule instead: every DOM
   * interface this shim implements must be exposed so `instanceof` answers, and the remaining seven
   * hundred are interfaces a server has no instances of. One reason beats seven hundred entries.
   *
   * What is left is the window's actual behaviour, and it is the same order as `document`.
   */
  "window": [
    "Atomics",
    "CSS",
    "GPUBufferUsage",
    "GPUColorWrite",
    "GPUMapMode",
    "GPUShaderStage",
    "GPUTextureUsage",
    "Infinity",
    "InstallTrigger",
    "Intl",
    "JSON",
    "KeyEvent",
    "Math",
    "NaN",
    "NodeFilter",
    "Proxy",
    "PublicKeyCredential",
    "Reflect",
    "SVGUnitTypes",
    "Temporal",
    "WebAssembly",
    "alert",
    "atob",
    "blur",
    "btoa",
    "caches",
    "cancelAnimationFrame",
    "cancelIdleCallback",
    "captureEvents",
    "clearInterval",
    "clearTimeout",
    "clientInformation",
    "close",
    "closed",
    "confirm",
    "console",
    "cookieStore",
    "crashReport",
    "createImageBitmap",
    "credentialless",
    "crossOriginIsolated",
    "crypto",
    "customElements",
    "decodeURI",
    "decodeURIComponent",
    "devicePixelRatio",
    "document",
    "documentPictureInPicture",
    "dump",
    "encodeURI",
    "encodeURIComponent",
    "escape",
    "eval",
    "event",
    "external",
    "fence",
    "fetch",
    "fetchLater",
    "find",
    "focus",
    "frameElement",
    "frames",
    "fullScreen",
    "getComputedStyle",
    "getDefaultComputedStyle",
    "getScreenDetails",
    "getSelection",
    "globalThis",
    "history",
    "indexedDB",
    "innerHeight",
    "innerWidth",
    "isFinite",
    "isNaN",
    "isSecureContext",
    "launchQueue",
    "length",
    "localStorage",
    "location",
    "locationbar",
    "matchMedia",
    "menubar",
    "moveBy",
    "moveTo",
    "mozInnerScreenX",
    "mozInnerScreenY",
    "name",
    "navigation",
    "navigator",
    "netscape",
    "offscreenBuffering",
    "open",
    "openDatabase",
    "opener",
    "origin",
    "originAgentCluster",
    "outerHeight",
    "outerWidth",
    "pageXOffset",
    "pageYOffset",
    "parent",
    "parseFloat",
    "parseInt",
    "performance",
    "personalbar",
    "postMessage",
    "print",
    "prompt",
    "pushManager",
    "queryLocalFonts",
    "queueMicrotask",
    "releaseEvents",
    "reportError",
    "requestAnimationFrame",
    "requestIdleCallback",
    "resizeBy",
    "resizeTo",
    "safari",
    "scheduler",
    "screen",
    "screenLeft",
    "screenTop",
    "screenX",
    "screenY",
    "scroll",
    "scrollBy",
    "scrollByLines",
    "scrollByPages",
    "scrollMaxX",
    "scrollMaxY",
    "scrollTo",
    "scrollX",
    "scrollY",
    "scrollbars",
    "self",
    "sessionStorage",
    "setInterval",
    "setResizable",
    "setTimeout",
    "sharedStorage",
    "showDirectoryPicker",
    "showOpenFilePicker",
    "showSaveFilePicker",
    "speechSynthesis",
    "status",
    "statusbar",
    "stop",
    "structuredClone",
    "styleMedia",
    "toolbar",
    "top",
    "trustedTypes",
    "undefined",
    "unescape",
    "updateCommands",
    "viewport",
    "visualViewport",
    "webkitCancelAnimationFrame",
    "webkitCancelRequestAnimationFrame",
    "webkitConvertPointFromNodeToPage",
    "webkitConvertPointFromPageToNode",
    "webkitIndexedDB",
    "webkitMediaStream",
    "webkitRTCPeerConnection",
    "webkitRequestAnimationFrame",
    "webkitRequestFileSystem",
    "webkitResolveLocalFileSystemURL",
    "webkitSpeechGrammar",
    "webkitSpeechGrammarList",
    "webkitSpeechRecognition",
    "webkitSpeechRecognitionError",
    "webkitSpeechRecognitionEvent",
    "webkitURL",
    "window"
  ],
  "tokenList": [
    "add",
    "contains",
    "entries",
    "forEach",
    "item",
    "keys",
    "length",
    "remove",
    "replace",
    "supports",
    "toString",
    "toggle",
    "value",
    "values"
  ]
};

/** Kept for the browser guard, which only checks the element. */
export const SURFACE = SURFACES.element;

/**
 * Members the shim deliberately does not have, and why.
 *
 * A stub that returns a plausible value is worse than one that is absent: `dispatchEvent: () => true`
 * passed every test written against it for as long as nobody asked what `true` meant. Anything that
 * cannot be answered honestly by a detached element holding a string is listed here instead.
 */
/**
 * The globals a component reaches for, and what a server can honestly give it.
 *
 * `true` means the shim provides it. A string is the reason it is deliberately **absent** — and
 * absent is a real answer here, not an oversight: a component that reads `localStorage` on a server
 * is reading state that belongs to one browser, and inventing an empty one renders a logged-out
 * shell the client immediately replaces. `typeof localStorage === 'undefined'` is the guard the
 * whole ecosystem already writes, and it only works if we do not lie.
 */
export const GLOBALS = {
  HTMLElement: true,
  Element: true,
  Node: true,
  ShadowRoot: true,
  DocumentFragment: true,
  Image: true,
  Audio: true,
  CSSStyleSheet: true,
  CSSScopeRule: true,
  Event: true,
  CustomEvent: true,
  EventTarget: true,
  customElements: true,
  document: true,
  window: true,
  location: true,
  history: true,
  navigator: true,
  requestAnimationFrame: true,
  cancelAnimationFrame: true,
  requestIdleCallback: true,
  cancelIdleCallback: true,
  matchMedia: true,
  getComputedStyle: true,
  getSelection: true,
  scrollTo: true,
  /** The other name for the global. `window` is defined, so a UMD bundle has already taken the browser branch. */
  self: true,
  addEventListener: true,
  removeEventListener: true,
  dispatchEvent: true,
  IntersectionObserver: true,
  ResizeObserver: true,
  MutationObserver: true,
  PerformanceObserver: true,

  /**
   * **The viewport family is absent on purpose, and the reason is not the same as `localStorage`'s.**
   * Nobody writes `typeof innerWidth === 'undefined'`, so the guard argument does not carry here.
   * What carries is consistency with `matchMedia`, which is *provided* and matches nothing: that is
   * the server saying "no media query applies", which renders the base shell. An `innerWidth` of `0`
   * would have the component beside it conclude it is on a zero-width phone and render the mobile
   * shell instead — two answers to the same question, from the same render. Absent, the read is a
   * `TypeError` the author fixes; present and zero, it is a wrong shell nobody sees until hydration
   * replaces it.
   */
  /**
   * **Only what `SURFACES.window` cannot speak for.** Every non-constructor global now lives in that
   * list with its reason in `OUT_OF_SCOPE.window`, so the absences that used to be repeated here —
   * `localStorage`, `screen`, `innerWidth` and the rest — were two hand-written reasons for one
   * fact, which is the arrangement this audit kept finding and removing. What stays is the half that
   * list does not reach: a constructor, or a global no engine exposes as an own property.
   *
   * `alert`, `confirm`, `prompt`, `open` and `print` were listed here as absent and are now inert,
   * which is the line that turned out to matter: **absent when a value would be read and would
   * contradict another answer here; inert when the call is an action with no consequence a server
   * can have.** `innerWidth` is the first — it would fight `matchMedia`. `alert` is the second —
   * a browser does not throw, nothing observes the result, and killing a render over it serves
   * nobody. `scrollTo` was already inert, so the shim had drawn this line before anyone wrote it
   * down.
   */
  DOMParser: 'parses HTML into a tree; nothing in this package parses HTML',
  XMLSerializer: 'serializes a tree; the markup is built as a string',
  Range: 'needs a tree',
  Selection: 'needs a tree and a user',
};

export const OUT_OF_SCOPE = {
  "window": {
    "CSS": "`CSS.supports` needs a CSS parser this DOM does not have, and a namespace answering half its members is worse than one that is absent — `typeof CSS === 'undefined'` is a guard someone can write",
    "GPUBufferUsage": "a WebGPU constant namespace; there is no adapter, no device and no canvas on a server",
    "GPUColorWrite": "a WebGPU constant namespace; there is no adapter, no device and no canvas on a server",
    "GPUMapMode": "a WebGPU constant namespace; there is no adapter, no device and no canvas on a server",
    "GPUShaderStage": "a WebGPU constant namespace; there is no adapter, no device and no canvas on a server",
    "GPUTextureUsage": "a WebGPU constant namespace; there is no adapter, no device and no canvas on a server",
    "InstallTrigger": "engine-specific or superseded, and absent from at least one of the three engines",
    "KeyEvent": "engine-specific or superseded, and absent from at least one of the three engines",
    "PublicKeyCredential": "a device or platform capability a server has no access to — WebAuthn needs an authenticator, and a render has neither a security key nor a person",
    "SVGUnitTypes": "engine-specific or superseded, and absent from at least one of the three engines",
    "Temporal": "a JavaScript proposal that arrives with the runtime, not something a DOM provides",
    "caches": "per-user state a server must not invent; guard with typeof",
    "clientInformation": "a legacy alias of `navigator`, which is provided",
    "cookieStore": "per-user state a server must not invent; guard with typeof",
    "crashReport": "engine-specific or superseded, and absent from at least one of the three engines",
    "createImageBitmap": "a device or platform capability a server has no access to",
    "credentialless": "a property of the browsing context that fetched the page, and a render has none",
    "crossOriginIsolated": "a property of the browsing context that fetched the page, and a render has none",
    "devicePixelRatio": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "documentPictureInPicture": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "dump": "engine-specific or superseded, and absent from at least one of the three engines",
    "event": "the legacy global `window.event`, superseded by the argument every listener already receives",
    "external": "engine-specific or superseded, and absent from at least one of the three engines",
    "fence": "a device or platform capability a server has no access to",
    "fetchLater": "a device or platform capability a server has no access to",
    "fullScreen": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "getDefaultComputedStyle": "Firefox-only; `getComputedStyle` is provided and answers empty for the same reason a detached element does",
    "getScreenDetails": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "indexedDB": "per-user state a server must not invent; guard with typeof",
    "innerHeight": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "innerWidth": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "isSecureContext": "a property of the browsing context that fetched the page, and a render has none",
    "launchQueue": "a device or platform capability a server has no access to",
    "localStorage": "per-user state a server must not invent; guard with typeof",
    "locationbar": "part of the browser window's own furniture, which a server render is not inside",
    "menubar": "part of the browser window's own furniture, which a server render is not inside",
    "mozInnerScreenX": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "mozInnerScreenY": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "navigation": "a device or platform capability a server has no access to",
    "netscape": "engine-specific or superseded, and absent from at least one of the three engines",
    "offscreenBuffering": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "openDatabase": "per-user state a server must not invent; guard with typeof",
    "originAgentCluster": "a property of the browsing context that fetched the page, and a render has none",
    "outerHeight": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "outerWidth": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "pageXOffset": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "pageYOffset": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "personalbar": "part of the browser window's own furniture, which a server render is not inside",
    "pushManager": "a device or platform capability a server has no access to",
    "queryLocalFonts": "a device or platform capability a server has no access to",
    "safari": "engine-specific or superseded, and absent from at least one of the three engines",
    "scheduler": "a device or platform capability a server has no access to",
    "screen": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "screenLeft": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "screenTop": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "screenX": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "screenY": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "scrollByLines": "engine-specific or superseded, and absent from at least one of the three engines",
    "scrollByPages": "engine-specific or superseded, and absent from at least one of the three engines",
    "scrollMaxX": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "scrollMaxY": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "scrollX": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "scrollY": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "scrollbars": "part of the browser window's own furniture, which a server render is not inside",
    "sessionStorage": "per-user state a server must not invent; guard with typeof",
    "setResizable": "engine-specific or superseded, and absent from at least one of the three engines",
    "sharedStorage": "per-user state a server must not invent; guard with typeof",
    "showDirectoryPicker": "a device or platform capability a server has no access to",
    "showOpenFilePicker": "a device or platform capability a server has no access to",
    "showSaveFilePicker": "a device or platform capability a server has no access to",
    "speechSynthesis": "a device or platform capability a server has no access to",
    "status": "part of the browser window's own furniture, which a server render is not inside",
    "statusbar": "part of the browser window's own furniture, which a server render is not inside",
    "styleMedia": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "toolbar": "part of the browser window's own furniture, which a server render is not inside",
    "trustedTypes": "a property of the browsing context that fetched the page, and a render has none",
    "updateCommands": "engine-specific or superseded, and absent from at least one of the three engines",
    "viewport": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "visualViewport": "needs a viewport or a display, and every other measurement in this DOM answers zero; a number here would contradict `matchMedia`, which matches nothing",
    "webkitCancelAnimationFrame": "engine-specific or superseded, and absent from at least one of the three engines",
    "webkitCancelRequestAnimationFrame": "engine-specific or superseded, and absent from at least one of the three engines",
    "webkitConvertPointFromNodeToPage": "engine-specific or superseded, and absent from at least one of the three engines",
    "webkitConvertPointFromPageToNode": "engine-specific or superseded, and absent from at least one of the three engines",
    "webkitIndexedDB": "per-user state a server must not invent; guard with typeof",
    "webkitMediaStream": "a device or platform capability a server has no access to",
    "webkitRTCPeerConnection": "a device or platform capability a server has no access to",
    "webkitRequestAnimationFrame": "engine-specific or superseded, and absent from at least one of the three engines",
    "webkitRequestFileSystem": "a device or platform capability a server has no access to",
    "webkitResolveLocalFileSystemURL": "a device or platform capability a server has no access to",
    "webkitSpeechGrammar": "a device or platform capability a server has no access to",
    "webkitSpeechGrammarList": "a device or platform capability a server has no access to",
    "webkitSpeechRecognition": "a device or platform capability a server has no access to",
    "webkitSpeechRecognitionError": "a device or platform capability a server has no access to",
    "webkitSpeechRecognitionEvent": "a device or platform capability a server has no access to",
    "webkitURL": "engine-specific or superseded, and absent from at least one of the three engines"
  },
  "tokenList": {},
  "element": {
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "customElementRegistry": "scoped registries; there is one registry here",
    "animate": "needs a compositor",
    "getAnimations": "needs a compositor",
    "startViewTransition": "needs a compositor",
    "activeViewTransition": "needs a compositor",
    "requestFullscreen": "needs a viewport and a user gesture",
    "webkitRequestFullscreen": "needs a viewport and a user gesture",
    "webkitRequestFullScreen": "needs a viewport and a user gesture",
    "mozRequestFullScreen": "needs a viewport and a user gesture",
    "requestPointerLock": "needs a viewport and a user gesture",
    "setPointerCapture": "needs a pointer",
    "releasePointerCapture": "needs a pointer",
    "hasPointerCapture": "needs a pointer",
    "setCapture": "needs a pointer",
    "releaseCapture": "needs a pointer",
    "scrollIntoViewIfNeeded": "needs layout; the standard scrollIntoView is a no-op here",
    "attributeStyleMap": "Typed OM; the string style view is what the markup carries",
    "computedStyleMap": "Typed OM, and there is no computed style without layout",
    "editContext": "needs an input method",
    "getHTML": "serializes shadow roots on demand; the SSR pipeline already decides that",
    "setHTML": "needs the Sanitizer API",
    "setHTMLUnsafe": "declarative shadow roots in a fragment; renderToString owns that decision",
    "outerText": "proprietary; innerText covers the reachable case",
    "accessKeyLabel": "derived from the platform keyboard",
    "pseudo": "set by the engine for pseudo-elements",
    "cue": "proprietary",
    "cuebackground": "proprietary",
    "webkitdropzone": "proprietary",
    "ariaNotify": "experimental, announces to a screen reader",
    "when": "experimental",
    "elementTiming": "reflects to an attribute only a performance observer reads",
    "focusGroup": "experimental",
    "focusGroupStart": "experimental",
    "headingOffset": "experimental",
    "headingReset": "experimental",
    "showPopover": "needs a top layer",
    "hidePopover": "needs a top layer",
    "togglePopover": "needs a top layer",
    "ariaActionsElements": "an element reference, not an attribute",
    "ariaActiveDescendantElement": "an element reference, not an attribute",
    "ariaControlsElements": "an element reference, not an attribute",
    "ariaDescribedByElements": "an element reference, not an attribute",
    "ariaDetailsElements": "an element reference, not an attribute",
    "ariaErrorMessageElements": "an element reference, not an attribute",
    "ariaFlowToElements": "an element reference, not an attribute",
    "ariaLabelledByElements": "an element reference, not an attribute",
    "ariaOwnsElements": "an element reference, not an attribute"
  },
  "shadowRoot": {
    "cloneNode": "the platform refuses to clone a shadow root (NotSupportedError)",
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "getAnimations": "needs a compositor",
    "when": "needs a compositor",
    "customElementRegistry": "scoped registries; there is one registry here",
    "getHTML": "serializes shadow roots on demand; renderToString owns that decision",
    "setHTML": "serializes shadow roots on demand; renderToString owns that decision",
    "setHTMLUnsafe": "serializes shadow roots on demand; renderToString owns that decision",
    "mozFullScreenElement": "engine-proprietary fullscreen"
  },
  "document": {
    "cloneNode": "this document is an object literal with a fixed body/head, not a container",
    "compareDocumentPosition": "this document is an object literal with a fixed body/head, not a container",
    "insertBefore": "this document is an object literal with a fixed body/head, not a container",
    "moveBefore": "this document is an object literal with a fixed body/head, not a container",
    "replaceChild": "this document is an object literal with a fixed body/head, not a container",
    "append": "this document is an object literal with a fixed body/head, not a container",
    "appendChild": "this document is an object literal with a fixed body/head, not a container",
    "prepend": "this document is an object literal with a fixed body/head, not a container",
    "replaceChildren": "this document is an object literal with a fixed body/head, not a container",
    "removeChild": "this document is an object literal with a fixed body/head, not a container",
    "firstChild": "this document is an object literal with a fixed body/head, not a container",
    "lastChild": "this document is an object literal with a fixed body/head, not a container",
    "nextSibling": "this document is an object literal with a fixed body/head, not a container",
    "previousSibling": "this document is an object literal with a fixed body/head, not a container",
    "parentNode": "this document is an object literal with a fixed body/head, not a container",
    "parentElement": "this document is an object literal with a fixed body/head, not a container",
    "normalize": "this document is an object literal with a fixed body/head, not a container",
    "isSameNode": "this document is an object literal with a fixed body/head, not a container",
    "isEqualNode": "this document is an object literal with a fixed body/head, not a container",
    "hasChildNodes": "this document is an object literal with a fixed body/head, not a container",
    "textContent": "this document is an object literal with a fixed body/head, not a container",
    "nodeValue": "this document is an object literal with a fixed body/head, not a container",
    "getRootNode": "this document is an object literal with a fixed body/head, not a container",
    "isConnected": "this document is an object literal with a fixed body/head, not a container",
    "ownerDocument": "this document is an object literal with a fixed body/head, not a container",
    "isDefaultNamespace": "needs a document to resolve namespaces against",
    "lookupNamespaceURI": "needs a document to resolve namespaces against",
    "lookupPrefix": "needs a document to resolve namespaces against",
    "createNSResolver": "needs a document to resolve namespaces against",
    "createExpression": "needs a document to resolve namespaces against",
    "evaluate": "needs a document to resolve namespaces against",
    "createAttribute": "node kinds this serializer does not emit",
    "createAttributeNS": "node kinds this serializer does not emit",
    "createCDATASection": "node kinds this serializer does not emit",
    "createProcessingInstruction": "node kinds this serializer does not emit",
  "createRange": "needs a tree, and a null stub would fail later and worse than an absent method",
          "createEvent": "node kinds this serializer does not emit",
    "createTouch": "node kinds this serializer does not emit",
    "createTouchList": "node kinds this serializer does not emit",
    "implementation": "node kinds this serializer does not emit",
    "rootElement": "node kinds this serializer does not emit",
    "xmlEncoding": "node kinds this serializer does not emit",
    "xmlStandalone": "node kinds this serializer does not emit",
    "xmlVersion": "node kinds this serializer does not emit",
    "fragmentDirective": "node kinds this serializer does not emit",
    "open": "document.open/write build a document by parsing; nothing here parses HTML",
    "close": "document.open/write build a document by parsing; nothing here parses HTML",
    "write": "document.open/write build a document by parsing; nothing here parses HTML",
    "writeln": "document.open/write build a document by parsing; nothing here parses HTML",
    "clear": "document.open/write build a document by parsing; nothing here parses HTML",
    "all": "document.open/write build a document by parsing; nothing here parses HTML",
    "captureEvents": "document.open/write build a document by parsing; nothing here parses HTML",
    "releaseEvents": "document.open/write build a document by parsing; nothing here parses HTML",
    "releaseCapture": "document.open/write build a document by parsing; nothing here parses HTML",
    "alinkColor": "legacy presentational attributes of <body>",
    "bgColor": "legacy presentational attributes of <body>",
    "fgColor": "legacy presentational attributes of <body>",
    "linkColor": "legacy presentational attributes of <body>",
    "vlinkColor": "legacy presentational attributes of <body>",
    "applets": "legacy presentational attributes of <body>",
    "domain": "legacy presentational attributes of <body>",
    "lastModified": "legacy presentational attributes of <body>",
    "wasDiscarded": "legacy presentational attributes of <body>",
    "prerendering": "legacy presentational attributes of <body>",
    "execCommand": "editing commands, which need a live selection",
    "queryCommandEnabled": "editing commands, which need a live selection",
    "queryCommandIndeterm": "editing commands, which need a live selection",
    "queryCommandState": "editing commands, which need a live selection",
    "queryCommandSupported": "editing commands, which need a live selection",
    "queryCommandValue": "editing commands, which need a live selection",
    "caretPositionFromPoint": "editing commands, which need a live selection",
    "caretRangeFromPoint": "editing commands, which need a live selection",
    "getCSSCanvasContext": "editing commands, which need a live selection",
    "mozSetImageElement": "editing commands, which need a live selection",
    "getAnimations": "needs a compositor",
    "startViewTransition": "needs a compositor",
    "activeViewTransition": "needs a compositor",
    "timeline": "needs a compositor",
    "fonts": "needs a compositor",
    "when": "needs a compositor",
    "ariaNotify": "needs a compositor",
    "exitFullscreen": "needs a viewport and a user gesture",
    "fullscreen": "needs a viewport and a user gesture",
    "fullscreenEnabled": "needs a viewport and a user gesture",
    "exitPictureInPicture": "needs a viewport and a user gesture",
    "pictureInPictureEnabled": "needs a viewport and a user gesture",
    "exitPointerLock": "needs a viewport and a user gesture",
    "mozCancelFullScreen": "needs a viewport and a user gesture",
    "mozFullScreen": "needs a viewport and a user gesture",
    "mozFullScreenElement": "needs a viewport and a user gesture",
    "mozFullScreenEnabled": "needs a viewport and a user gesture",
    "webkitCancelFullScreen": "needs a viewport and a user gesture",
    "webkitCurrentFullScreenElement": "needs a viewport and a user gesture",
    "webkitExitFullscreen": "needs a viewport and a user gesture",
    "webkitFullScreenKeyboardInputAllowed": "needs a viewport and a user gesture",
    "webkitFullscreenElement": "needs a viewport and a user gesture",
    "webkitFullscreenEnabled": "needs a viewport and a user gesture",
    "webkitIsFullScreen": "needs a viewport and a user gesture",
    "webkitHidden": "needs a viewport and a user gesture",
    "webkitVisibilityState": "needs a viewport and a user gesture",
    "enableStyleSheetsForSet": "needs a viewport and a user gesture",
    "lastStyleSheetSet": "needs a viewport and a user gesture",
    "preferredStyleSheetSet": "needs a viewport and a user gesture",
    "selectedStyleSheetSet": "needs a viewport and a user gesture",
    "styleSheetSets": "needs a viewport and a user gesture",
    "cookie": "per-user state a server must not invent",
    "hasStorageAccess": "per-user state a server must not invent",
    "requestStorageAccess": "per-user state a server must not invent",
    "requestStorageAccessFor": "per-user state a server must not invent",
    "hasPrivateToken": "per-user state a server must not invent",
    "hasRedemptionRecord": "per-user state a server must not invent",
    "hasUnpartitionedCookieAccess": "per-user state a server must not invent",
    "browsingTopics": "per-user state a server must not invent",
    "featurePolicy": "per-user state a server must not invent",
    "customElementRegistry": "scoped registries; there is one registry here",
    "getHTML": "serializes on demand; renderToString owns that decision",
    "setHTML": "serializes on demand; renderToString owns that decision",
    "setHTMLUnsafe": "serializes on demand; renderToString owns that decision"
  },
  "sheet": {}
};
