/**
 * **`serializeValue` stays small enough for V8 to inline** (2026-10-09). It runs for every binding of every server
 * render, inside `serializeTemplate`'s loop, and V8 inlines it there only while its bytecode is at most
 * `--max-inlined-bytecode-size` (460 by default). It sat at 455. The DOM-node case took it to 467, and every render
 * paid 3.6% steady — including renders that never reach the case: a bisect over the change's three parts showed the
 * import and the alias free, and a never-taken branch alone +4.0% (V8's trace: "Cannot consider serializeValue for
 * inlining (reason: 5)", too big). Moving a refusal's error construction out of line brought it to 421.
 *
 * No code read shows this, and no correctness test can: so the budget is asserted here, read from the V8 this Node
 * runs (both the function's bytecode length and the limit), rather than remembered.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const root = new URL('..', import.meta.url);

test("serializeValue's bytecode fits V8's inlining budget", (t) => {
  const limit = Number(/--max-inlined-bytecode-size=(\d+)/.exec(execFileSync(process.execPath, ['--v8-options'], { encoding: 'utf8' }))?.[1]);
  assert.ok(limit > 0, `CONTROL: read the inlining limit from this V8 (${limit})`);
  const printed = execFileSync(process.execPath, [
    ...process.execArgv, '--print-bytecode', '--print-bytecode-filter=serializeValue', '--input-type=module', '-e',
    "const ssr = await import('@verajs/ssr'); const { html } = await import('@verajs/core'); for (let i = 0; i < 3; i++) ssr.serializeTemplate(html`<p>${'x'}</p>`);",
  ], { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  const length = Number(/generated bytecode for function: serializeValue [\s\S]*?Bytecode length: (\d+)/.exec(printed)?.[1]);
  /** A parse that reads nothing must go red, not pass: a Node whose --print-bytecode output changed would otherwise
   *  measure nothing and report a perfect fit. The function is ~400 bytes; anything under 100 is a misread. */
  assert.ok(length > 100, `CONTROL: read serializeValue's bytecode length from V8 (${length}) — has --print-bytecode's output changed?`);
  /** The headroom, every run: a reviewer sees it shrink before the next change falls off the cliff. */
  t.diagnostic(`serializeValue: ${length} of ${limit} bytes of bytecode — ${limit - length} to spare`);
  assert.ok(length <= limit, `serializeValue is ${length} bytes of bytecode, over V8's inlining limit of ${limit}: move a rarely-run piece (an error's construction, a rare branch) out of line — see this file`);
});
