import { describe, it, beforeEach, afterEach } from './harness.mjs';
import { expect, vi } from './expect.mjs';
import { createMotion } from '../src/index.ts';
import { createScrollTo } from '../src/scroll-to.ts';

/**
 * Two options that took the wrong *type* rather than the wrong value.
 *
 * The consumer of this library is a WordPress plugin whose JavaScript is
 * generated by PHP, so a number where a node belongs is not an exotic mistake —
 * it is a field left at `0`, or a cast that did not happen. Every *value* has
 * been checked since decision 31; the types had not.
 */
const P = 'data-vm';

beforeEach(() => {
  vi.spyOn(console, 'warn').mockImplementation(() => {});
  vi.stubGlobal('requestAnimationFrame', (fn) => { fn(0); return 1; });
  vi.stubGlobal('cancelAnimationFrame', () => {});
  document.body.innerHTML = `<div ${P} ${P}-opacity="0% 0, 100% 1"></div>`;
});
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });

const reasons = (m) => m.rejected.filter((entry) => entry.node === null).flatMap((entry) => entry.rejected ?? [entry.reason]);

describe('scrollElement that is not an element or a selector', () => {
  for (const [name, value] of [['a number', 42], ['a plain object', {}], ['true', true]]) {
    it(`falls back to the window when it is ${name}`, () => {
      const m = createMotion({ respectReducedMotion: false, inertia: 0, scrollElement: value });
      m.init();

      expect(m.elements, 'the page still animates').toHaveLength(1);
      expect(reasons(m).join(' ')).toContain('scrollElement is not an element');
      m.destroy();
    });
  }

  /** `scroll-to` shares the resolver, so it shares the fix. */
  it('and scroll-to says so too', () => {
    document.body.innerHTML = '<a href="#t">go</a><div id="t"></div>';
    const s = createScrollTo({ scrollElement: 42 });
    s.init();
    expect(s.rejected.map((entry) => entry.reason).join(' ')).toContain('scrollElement is not an element');
    s.destroy();
  });

  /** A real one still resolves, which is the control. */
  it('while a real element is still used', () => {
    document.body.innerHTML = `<div id="pane"><div ${P} ${P}-opacity="0% 0, 100% 1"></div></div>`;
    const m = createMotion({
      respectReducedMotion: false, inertia: 0, scrollElement: document.getElementById('pane'),
    });
    m.init();
    expect(m.rejected).toEqual([]);
    m.destroy();
  });
});

/**
 * `inertia` is an option *and* an attribute, and only the attribute was
 * range-checked: `data-vm-inertia="-1"` was refused and reported while
 * `createMotion({ inertia: -1 })` was accepted in silence and produced no
 * transition at all — `inertia: 0` reached by a sign error, with nothing said.
 */
describe('an inertia option outside the range the attribute uses', () => {
  for (const value of [-1, 4000]) {
    it(`reports ${value} and falls back`, () => {
      const m = createMotion({ respectReducedMotion: false, inertia: value });
      m.init();
      expect(reasons(m).join(' ')).toContain('inertia');
      m.destroy();
    });
  }

  it('and leaves a value inside it alone', () => {
    const m = createMotion({ respectReducedMotion: false, inertia: 0.4 });
    m.init();
    expect(m.rejected).toEqual([]);
    m.destroy();
  });

  /** Zero is inside the range and means "no transition", not "not usable". */
  it('including zero, which is a real setting', () => {
    const m = createMotion({ respectReducedMotion: false, inertia: 0 });
    m.init();
    expect(m.rejected).toEqual([]);
    m.destroy();
  });
});
