import { describe, it, beforeEach, afterEach } from './harness.mjs';
import { expect, vi } from './expect.mjs';
import { createMotion } from '../src/index.ts';

/**
 * `root` is typed `ParentNode`, and the consumer of this library is a WordPress
 * plugin whose JavaScript is generated by PHP — there is no compiler between
 * that and here.
 *
 * A string is the obvious thing to try, because `scrollElement` accepts one in
 * both entry points and the README says so. It threw `root.querySelectorAll is
 * not a function` **out of `init()`**, which takes the page's own script down
 * with it. `observe()` was worse: it added the value to `roots` and then threw,
 * so one bad call poisoned the instance — every later `collect()` and the
 * `destroy()` threw on the same value.
 */
const P = 'data-vera-motion';
const JUNK = [['null', null], ['a string', 'body'], ['a number', 7], ['a plain object', {}]];

beforeEach(() => {
  vi.spyOn(console, 'warn').mockImplementation(() => {});
  vi.stubGlobal('requestAnimationFrame', (fn) => { fn(0); return 1; });
  vi.stubGlobal('cancelAnimationFrame', () => {});
  document.body.innerHTML = `<div ${P} ${P}-opacity="0% 0, 100% 1"></div>`;
});
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });

const reasons = (m) => m.rejected.filter((entry) => entry.node === null).flatMap((entry) => entry.rejected);

describe('a root that is not a node', () => {
  for (const [name, value] of JUNK) {
    it(`falls back to the document when the option is ${name}`, () => {
      const m = createMotion({ respectReducedMotion: false, inertia: 0, root: value });
      m.init();

      expect(m.elements, 'the document is scanned instead').toHaveLength(1);
      expect(reasons(m).join(' ')).toContain('root is not an element');
      m.destroy();
    });

    it(`refuses observe(${name}) without poisoning the instance`, () => {
      const m = createMotion({ respectReducedMotion: false, inertia: 0 });
      m.init();

      m.observe(value);

      expect(reasons(m).join(' ')).toContain('observe()');
      /** The proof it is not poisoned: everything after still works. */
      m.collect();
      expect(m.elements).toHaveLength(1);
      m.refresh();
      m.destroy();
      expect(document.querySelector(`[${P}]`).style.filter).toBe('');
    });
  }

  /** A real root still works, which is the control. */
  it('and a real one is still adopted', () => {
    document.body.innerHTML = `<div id="host"><div ${P} ${P}-opacity="0% 0, 100% 1"></div></div>`;
    const m = createMotion({ respectReducedMotion: false, inertia: 0, root: document.getElementById('host') });
    m.init();
    expect(m.elements).toHaveLength(1);
    expect(m.rejected).toEqual([]);
    m.destroy();
  });
});

/**
 * `root` takes one node or an array of them — one name, both shapes, the same
 * pattern `wireMotion` sets. A junk entry in an array is reported by position
 * and skipped, and losing every candidate never yields an instance that
 * silently watches nothing.
 */
describe('root as an array', () => {
  it('watches exactly the listed subtrees and nothing else', () => {
    document.body.innerHTML = `
      <nav><div ${P} ${P}-opacity="0% 0, 100% 1"></div></nav>
      <section id="hero"><div ${P} ${P}-opacity="0% 0, 100% 1"></div></section>
      <footer><div ${P} ${P}-opacity="0% 0, 100% 1"></div></footer>`;
    const m = createMotion({
      respectReducedMotion: false, inertia: 0,
      root: [document.querySelector('nav'), document.querySelector('#hero')],
    });
    m.init();
    expect(m.elements, 'nav and hero are watched; the footer is not').toHaveLength(2);
    expect(reasons(m)).toEqual([]);
    m.destroy();
  });

  it('a one-element array behaves like the single form', () => {
    document.body.innerHTML = `
      <nav><div ${P} ${P}-opacity="0% 0, 100% 1"></div></nav>
      <section><div ${P} ${P}-opacity="0% 0, 100% 1"></div></section>`;
    const m = createMotion({
      respectReducedMotion: false, inertia: 0,
      root: [document.querySelector('nav')],
    });
    m.init();
    expect(m.elements).toHaveLength(1);
    m.destroy();
  });

  it('reports a junk entry by position, keeps the usable ones', () => {
    document.body.innerHTML = `<nav><div ${P} ${P}-opacity="0% 0, 100% 1"></div></nav>`;
    const m = createMotion({
      respectReducedMotion: false, inertia: 0,
      root: [document.querySelector('nav'), 'body'],
    });
    m.init();
    expect(m.elements, 'the usable root still works').toHaveLength(1);
    expect(reasons(m).join(' ')).toContain('root[1]');
    m.destroy();
  });

  it('falls back to the document when the array holds nothing usable', () => {
    const m = createMotion({ respectReducedMotion: false, inertia: 0, root: [null, 'body'] });
    m.init();
    expect(m.elements, 'the document is scanned instead').toHaveLength(1);
    expect(reasons(m).join(' ')).toContain('root[0]');
    m.destroy();
  });
});
