/** GENERATED by scripts/build-hydration-fixture.mjs — real @verajs/ssr output. Do not edit. */
export const SERVER_HTML = "<hello-ssr><template shadowrootmode=\"open\">\n        <section class=\"wrap\">\n          <h1>hello from the server</h1>\n          <output>count: 3</output>\n          <input value=\"hello from the server\" />\n        </section>\n      </template></hello-ssr>";
